// Generated by GitHub Copilot
import type { ProjectIntegration } from "../types";

/**
 * Resolves integration endpoints from build-time environment values with local defaults.
 */
function resolveIntegrationUrl(envValue: string | undefined, fallbackUrl: string): string {
  const trimmedValue = envValue?.trim();
  if (trimmedValue) {
    return trimmedValue;
  }
  return fallbackUrl;
}

export const PROJECTS: ProjectIntegration[] = [
  {
    id: "drift-watch",
    name: "drift-watch",
    tagline: "Production ML drift observability",
    category: "observability",
    kind: "frontend",
    launchMode: "iframe",
    url: resolveIntegrationUrl(import.meta.env.VITE_DRIFT_WATCH_URL, "http://localhost:5401"),
    healthUrl: resolveIntegrationUrl(import.meta.env.VITE_DRIFT_WATCH_URL, "http://localhost:5401"),
    startCommand: "npm --prefix ..\\drift-watch\\frontend run dev -- --port 5401 --host",
    repoPath: "..\\drift-watch",
    statusNote: "Feature and concept drift control center"
  },
  {
    id: "llm-judge",
    name: "llm-judge",
    tagline: "LLM evaluation and scoring",
    category: "observability",
    kind: "frontend",
    launchMode: "iframe",
    url: resolveIntegrationUrl(import.meta.env.VITE_LLM_JUDGE_URL, "http://localhost:5402"),
    healthUrl: resolveIntegrationUrl(import.meta.env.VITE_LLM_JUDGE_URL, "http://localhost:5402"),
    startCommand: "npm --prefix ..\\llm-judge\\frontend run dev -- --port 5402 --host",
    repoPath: "..\\llm-judge",
    statusNote: "Judge runs, metrics, and leaderboard"
  },
  {
    id: "ragbench",
    name: "ragbench",
    tagline: "RAG benchmark harness",
    category: "observability",
    kind: "frontend",
    launchMode: "iframe",
    url: resolveIntegrationUrl(import.meta.env.VITE_RAGBENCH_URL, "http://localhost:5403"),
    healthUrl: resolveIntegrationUrl(import.meta.env.VITE_RAGBENCH_URL, "http://localhost:5403"),
    startCommand: "npm --prefix ..\\ragbench\\frontend run dev -- --port 5403 --host",
    repoPath: "..\\ragbench",
    statusNote: "Retrieval and answer-quality benchmarking"
  },
  {
    id: "prompt-ops",
    name: "prompt-ops",
    tagline: "Prompt lifecycle command center",
    category: "agentics",
    kind: "frontend",
    launchMode: "iframe",
    url: resolveIntegrationUrl(import.meta.env.VITE_PROMPT_OPS_URL, "http://localhost:5404"),
    healthUrl: resolveIntegrationUrl(import.meta.env.VITE_PROMPT_OPS_URL, "http://localhost:5404"),
    startCommand: "npm --prefix ..\\prompt-ops\\frontend run dev -- --port 5404 --host",
    repoPath: "..\\prompt-ops",
    statusNote: "Versioning, experiments, promotion"
  },
  {
    id: "neuralscope",
    name: "neuralscope",
    tagline: "Model graph and gradient debugger",
    category: "observability",
    kind: "frontend",
    launchMode: "iframe",
    url: resolveIntegrationUrl(import.meta.env.VITE_NEURALSCOPE_URL, "http://localhost:5405"),
    healthUrl: resolveIntegrationUrl(import.meta.env.VITE_NEURALSCOPE_URL, "http://localhost:5405"),
    startCommand: "npm --prefix ..\\neuralscope\\frontend run dev -- --port 5405 --host",
    repoPath: "..\\neuralscope",
    statusNote: "Detect dead neurons and activation drift"
  },
  {
    id: "config-forge",
    name: "config-forge",
    tagline: "Model config governance",
    category: "platform",
    kind: "frontend",
    launchMode: "iframe",
    url: resolveIntegrationUrl(import.meta.env.VITE_CONFIG_FORGE_URL, "http://localhost:5406"),
    healthUrl: resolveIntegrationUrl(import.meta.env.VITE_CONFIG_FORGE_URL, "http://localhost:5406"),
    startCommand: "npm --prefix ..\\config-forge\\frontend run dev -- --port 5406 --host",
    repoPath: "..\\config-forge",
    statusNote: "Validate and promote serving configs"
  },
  {
    id: "interview-os",
    name: "interview-os",
    tagline: "Interview orchestration workspace",
    category: "platform",
    kind: "frontend",
    launchMode: "iframe",
    url: resolveIntegrationUrl(import.meta.env.VITE_INTERVIEW_OS_URL, "http://localhost:5407"),
    healthUrl: resolveIntegrationUrl(import.meta.env.VITE_INTERVIEW_OS_URL, "http://localhost:5407"),
    startCommand: "npm --prefix ..\\interview-os\\frontend run dev -- --port 5407 --host",
    repoPath: "..\\interview-os",
    statusNote: "Structured kits, sessions, and hiring recs"
  },
  {
    id: "mlops-sentinel",
    name: "mlops-sentinel",
    tagline: "MLOps monitoring dashboard",
    category: "observability",
    kind: "frontend",
    launchMode: "iframe",
    url: resolveIntegrationUrl(import.meta.env.VITE_MLOPS_SENTINEL_URL, "http://localhost:5408"),
    healthUrl: resolveIntegrationUrl(import.meta.env.VITE_MLOPS_SENTINEL_URL, "http://localhost:5408"),
    startCommand: "npm --prefix ..\\mlops-sentinel\\frontend run dev -- --port 5408 --host",
    repoPath: "..\\mlops-sentinel",
    statusNote: "Model and service reliability monitoring"
  },
  {
    id: "agent-tracer",
    name: "agent-tracer",
    tagline: "Trace visualizer for agent execution",
    category: "agentics",
    kind: "frontend",
    launchMode: "iframe",
    url: resolveIntegrationUrl(import.meta.env.VITE_AGENT_TRACER_URL, "http://localhost:5409"),
    healthUrl: resolveIntegrationUrl(import.meta.env.VITE_AGENT_TRACER_URL, "http://localhost:5409"),
    startCommand: "npm --prefix ..\\agent-tracer\\frontend run dev -- --port 5409 --host",
    repoPath: "..\\agent-tracer",
    statusNote: "Timeline and flow introspection"
  },
  {
    id: "agentic-research-assistant",
    name: "agentic-research-assistant",
    tagline: "Research orchestration assistant",
    category: "agentics",
    kind: "frontend",
    launchMode: "iframe",
    url: resolveIntegrationUrl(
      import.meta.env.VITE_AGENTIC_RESEARCH_ASSISTANT_URL,
      "http://localhost:5410"
    ),
    healthUrl: resolveIntegrationUrl(
      import.meta.env.VITE_AGENTIC_RESEARCH_ASSISTANT_URL,
      "http://localhost:5410"
    ),
    startCommand:
      "npm --prefix ..\\agentic-research-assistant\\frontend run dev -- --port 5410 --host",
    repoPath: "..\\agentic-research-assistant",
    statusNote: "Search, summarize, critique, and assemble"
  },
  {
    id: "agentic-ui",
    name: "agentic-ui",
    tagline: "Shared components and Storybook",
    category: "agentics",
    kind: "storybook",
    launchMode: "iframe",
    url: resolveIntegrationUrl(import.meta.env.VITE_AGENTIC_UI_URL, "http://localhost:6006"),
    healthUrl: resolveIntegrationUrl(import.meta.env.VITE_AGENTIC_UI_URL, "http://localhost:6006"),
    startCommand: "npm --prefix ..\\agentic-ui run storybook -- --port 6006",
    repoPath: "..\\agentic-ui",
    statusNote: "Agent interaction design system"
  },
  {
    id: "context-watchdog",
    name: "context-watchdog",
    tagline: "Policy enforcement runtime",
    category: "platform",
    kind: "documentation",
    launchMode: "external",
    url: resolveIntegrationUrl(
      import.meta.env.VITE_CONTEXT_WATCHDOG_URL,
      "https://github.com/Ramdragneel01/context-watchdog"
    ),
    startCommand: "python -m pip install -r ..\\context-watchdog\\requirements.txt",
    repoPath: "..\\context-watchdog",
    statusNote: "Python package with integrations and policy recipes"
  }
];
