// Generated by GitHub Copilot
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

/**
 * Resolves Vite base path for GitHub Pages while keeping local development on root.
 */
function resolveBasePath(): string {
  const explicitBasePath = process.env.VITE_BASE_PATH;
  if (explicitBasePath) {
    return explicitBasePath;
  }

  if (process.env.GITHUB_ACTIONS === "true") {
    const repoName = process.env.GITHUB_REPOSITORY?.split("/")[1];
    if (repoName) {
      return `/${repoName}/`;
    }
  }

  return "/";
}

export default defineConfig({
  plugins: [react()],
  base: resolveBasePath(),
  server: {
    port: 4300,
    host: true
  }
});
