// Generated by GitHub Copilot
import { useState, type FormEvent } from "react";

interface AgentChatDockProps {
    activeModuleName?: string;
}

type ChatRole = "assistant" | "user";

interface ChatMessage {
    id: string;
    role: ChatRole;
    content: string;
    timestampIso: string;
}

/**
 * Returns concise assistant guidance tied to the operator's prompt.
 */
function buildAssistantReply(input: string, activeModuleName?: string): string {
    const normalized = input.toLowerCase();

    if (normalized.includes("health") || normalized.includes("backend") || normalized.includes("offline")) {
        return "Check the module status badge first. If it is offline, run the startup command in this panel, then trigger Retry health check.";
    }

    if (normalized.includes("theme") || normalized.includes("color") || normalized.includes("ui")) {
        return "Use the theme toggle in the header for quick switching. The shell now applies updated contrast tokens for cards, pills, and panel surfaces.";
    }

    if (normalized.includes("deploy") || normalized.includes("production")) {
        return "For production readiness, keep module URLs in environment variables and validate health checks from a server-side probe before enabling deployment.";
    }

    if (activeModuleName) {
        return `I can help with ${activeModuleName}. Ask for startup commands, health troubleshooting, or role access checks.`;
    }

    return "I can help with module startup, status troubleshooting, theme tweaks, and safe rollout steps.";
}

/**
 * Formats a local time label for each chat bubble.
 */
function formatTimestamp(isoValue: string): string {
    const parsed = new Date(isoValue);
    if (Number.isNaN(parsed.getTime())) {
        return "now";
    }

    return parsed.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

function ChatBubbleIcon() {
    return (
        <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
            <path
                d="M4 5.5A2.5 2.5 0 0 1 6.5 3h11A2.5 2.5 0 0 1 20 5.5v7A2.5 2.5 0 0 1 17.5 15H10l-4.8 4v-4A2.5 2.5 0 0 1 4 12.5v-7Z"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.7"
                strokeLinejoin="round"
            />
            <circle cx="9" cy="9" r="1" fill="currentColor" />
            <circle cx="12" cy="9" r="1" fill="currentColor" />
            <circle cx="15" cy="9" r="1" fill="currentColor" />
        </svg>
    );
}

function SendIcon() {
    return (
        <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
            <path
                d="M3.4 11.8 20 4.2l-3.6 15.6-5.5-5.2-7.5-2.8Zm7.1 2.3 3.8 3.6 2.1-9.1-9.8 4.5 3.9 1.4Z"
                fill="currentColor"
            />
        </svg>
    );
}

/**
 * Floating assistant dock inspired by partner-portal chat behavior.
 */
export function AgentChatDock({ activeModuleName }: AgentChatDockProps) {
    const [isOpen, setIsOpen] = useState(false);
    const [isResponding, setIsResponding] = useState(false);
    const [draft, setDraft] = useState("");
    const [messages, setMessages] = useState<ChatMessage[]>([
        {
            id: "bootstrap-assistant",
            role: "assistant",
            content:
                "AstraMesh Copilot is ready. Ask about module health, startup commands, or UI configuration.",
            timestampIso: new Date().toISOString()
        }
    ]);

    function submitMessage(event: FormEvent<HTMLFormElement>) {
        event.preventDefault();
        const trimmedDraft = draft.trim();
        if (!trimmedDraft) {
            return;
        }

        const userMessage: ChatMessage = {
            id: `user-${Date.now()}`,
            role: "user",
            content: trimmedDraft,
            timestampIso: new Date().toISOString()
        };

        setMessages((existingMessages) => [...existingMessages, userMessage]);
        setDraft("");
        setIsResponding(true);

        window.setTimeout(() => {
            const assistantMessage: ChatMessage = {
                id: `assistant-${Date.now()}`,
                role: "assistant",
                content: buildAssistantReply(trimmedDraft, activeModuleName),
                timestampIso: new Date().toISOString()
            };
            setMessages((existingMessages) => [...existingMessages, assistantMessage]);
            setIsResponding(false);
        }, 280);
    }

    return (
        <>
            <button
                type="button"
                className={isOpen ? "chat-launcher open" : "chat-launcher"}
                onClick={() => setIsOpen((previous) => !previous)}
                aria-expanded={isOpen}
                aria-controls="astramesh-chat-dock"
            >
                <span className="chat-launcher-icon" aria-hidden="true">
                    <ChatBubbleIcon />
                </span>
                <span className="chat-launcher-label">{isOpen ? "Close Mesh Chat" : "Open Mesh Chat"}</span>
            </button>

            <button
                type="button"
                className={isOpen ? "chat-backdrop open" : "chat-backdrop"}
                onClick={() => setIsOpen(false)}
                aria-label="Close mesh chat"
                tabIndex={isOpen ? 0 : -1}
            />

            <aside
                id="astramesh-chat-dock"
                className={isOpen ? "chat-dock open" : "chat-dock"}
                aria-label="AstraMesh assistant chat"
            >
                <header className="chat-dock-header">
                    <div>
                        <p className="chat-eyebrow">Assistant</p>
                        <h3>AstraMesh Copilot</h3>
                        <p className="chat-module-context">
                            {activeModuleName ? `Context: ${activeModuleName}` : "Context: AstraMesh Shell"}
                        </p>
                    </div>
                    <button type="button" className="chat-close" onClick={() => setIsOpen(false)}>
                        Close
                    </button>
                </header>

                <div className="chat-dock-body" role="log" aria-live="polite">
                    {messages.map((message) => (
                        <article
                            key={message.id}
                            className={
                                message.role === "assistant" ? "chat-message chat-message-assistant" : "chat-message chat-message-user"
                            }
                        >
                            <p>{message.content}</p>
                            <small>{formatTimestamp(message.timestampIso)}</small>
                        </article>
                    ))}

                    {isResponding ? (
                        <p className="chat-thinking" role="status">
                            Assistant is thinking...
                        </p>
                    ) : null}
                </div>

                <form className="chat-input-row" onSubmit={submitMessage}>
                    <input
                        type="text"
                        value={draft}
                        onChange={(event) => setDraft(event.target.value)}
                        placeholder="Ask about status, startup, or theme..."
                        aria-label="Chat message"
                    />
                    <button type="submit" aria-label="Send message" disabled={isResponding || draft.trim().length === 0}>
                        <SendIcon />
                    </button>
                </form>
            </aside>
        </>
    );
}
