// Generated by GitHub Copilot
import { Link } from "react-router-dom";
import type { ProjectIntegration } from "../types";

interface ProjectCardsProps {
  projects: ProjectIntegration[];
}

/**
 * Dashboard cards help operators discover all integrated modules and jump into any workspace.
 */
export function ProjectCards({ projects }: ProjectCardsProps) {
  if (projects.length === 0) {
    return (
      <section aria-labelledby="dashboard-title">
        <h2 id="dashboard-title">Integrated Modules</h2>
        <p className="panel-copy">
          No modules are assigned to the selected role. Change access role in the header to view
          other workspaces.
        </p>
      </section>
    );
  }

  return (
    <section aria-labelledby="dashboard-title">
      <h2 id="dashboard-title">Integrated Modules</h2>
      <p className="panel-copy">
        Select a module to open its live workspace panel. If a module is offline, use the startup
        command shown in the workspace view.
      </p>

      <div className="card-grid">
        {projects.map((project) => (
          <article key={project.id} className="module-card" aria-label={`${project.name} card`}>
            <p className="module-kind">{project.kind}</p>
            <h3>{project.name}</h3>
            <p>{project.tagline}</p>
            <p className="status-note">{project.statusNote}</p>
            <p className="module-roles">Roles: {project.allowedRoles.join(", ")}</p>
            <div className="card-actions">
              <Link to={`/workspace/${project.id}`}>Open workspace</Link>
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}
