// Generated by GitHub Copilot
import { Link } from "react-router-dom";
import type { PropsWithChildren } from "react";
import type { ProjectIntegration } from "../types";

interface ShellLayoutProps {
  projects: ProjectIntegration[];
  activeProjectId?: string;
}

/**
 * Groups projects by category so the side navigation stays scannable at scale.
 */
function groupProjectsByCategory(
  projects: ProjectIntegration[]
): Record<string, ProjectIntegration[]> {
  return projects.reduce<Record<string, ProjectIntegration[]>>((accumulator, project) => {
    if (!accumulator[project.category]) {
      accumulator[project.category] = [];
    }
    accumulator[project.category].push(project);
    return accumulator;
  }, {});
}

/**
 * Layout shell that mirrors partner-portal host behavior with global nav + content frame.
 */
export function ShellLayout({
  projects,
  activeProjectId,
  children
}: PropsWithChildren<ShellLayoutProps>) {
  const categorizedProjects = groupProjectsByCategory(projects);
  const categoryOrder = ["platform", "agentics", "observability"];

  return (
    <div className="shell-root">
      <header className="shell-header">
        <div>
          <p className="eyebrow">AstraMesh Federation Host</p>
          <h1>AstraMesh Command Deck</h1>
          <p className="header-subtitle">
            One UI for your full app portfolio. Launch, inspect, and operate every module from a
            single shell.
          </p>
        </div>
        <div className="header-stats" aria-label="Project totals">
          <span>{projects.length} modules</span>
          <span>Route-based workspace</span>
          <span>Partner-portal style shell</span>
        </div>
      </header>

      <div className="shell-body">
        <aside className="shell-sidebar" aria-label="Project navigation">
          <nav>
            <Link className="side-link side-link-home" to="/dashboard">
              Overview
            </Link>

            {categoryOrder.map((category) => {
              const items = categorizedProjects[category] ?? [];
              if (items.length === 0) {
                return null;
              }

              return (
                <section key={category} className="side-section">
                  <h2>{category}</h2>
                  <ul>
                    {items.map((project) => {
                      const isActive = project.id === activeProjectId;
                      return (
                        <li key={project.id}>
                          <Link
                            className={isActive ? "side-link active" : "side-link"}
                            to={`/workspace/${project.id}`}
                          >
                            {project.name}
                          </Link>
                        </li>
                      );
                    })}
                  </ul>
                </section>
              );
            })}
          </nav>
        </aside>

        <main id="main-content" className="shell-main">
          {children}
        </main>
      </div>
    </div>
  );
}
