// Generated by GitHub Copilot
import { Link } from "react-router-dom";
import { useRef, useState, type PropsWithChildren } from "react";
import { AgentChatDock } from "./AgentChatDock";
import { ROLE_OPTIONS } from "../utils/access";
import type { IntegrationKind, ProjectIntegration, ThemeMode, UserRole } from "../types";

interface ShellLayoutProps {
  projects: ProjectIntegration[];
  activeProjectId?: string;
  totalProjects: number;
  currentRole: UserRole;
  onRoleChange: (nextRole: UserRole) => void;
  currentTheme: ThemeMode;
  onThemeToggle: () => void;
}

/**
 * Groups projects by category so the side navigation stays scannable at scale.
 */
function groupProjectsByCategory(
  projects: ProjectIntegration[]
): Record<string, ProjectIntegration[]> {
  return projects.reduce<Record<string, ProjectIntegration[]>>((accumulator, project) => {
    if (!accumulator[project.category]) {
      accumulator[project.category] = [];
    }
    accumulator[project.category].push(project);
    return accumulator;
  }, {});
}

function ThemeSunIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <circle cx="12" cy="12" r="4.2" fill="currentColor" />
      <path
        d="M12 2.5v2.2M12 19.3v2.2M2.5 12h2.2M19.3 12h2.2M5.4 5.4l1.6 1.6M17 17l1.6 1.6M18.6 5.4L17 7M7 17l-1.6 1.6"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
        fill="none"
      />
    </svg>
  );
}

function ThemeMoonIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M15.7 3.7a8.7 8.7 0 1 0 4.6 15.6A9.1 9.1 0 0 1 15.7 3.7Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function HomeIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M4 11.2 12 4l8 7.2V20h-5.2v-5.4H9.2V20H4v-8.8Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function UserIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M12 12.1a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm-6.1 6.8a6.1 6.1 0 0 1 12.2 0"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function ChevronLeftIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M14.5 6.5 9 12l5.5 5.5"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function ChevronRightIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M9.5 6.5 15 12l-5.5 5.5"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function SlidersIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M5 6h14M5 12h14M5 18h14M9 4.5v3M15 10.5v3M12 16.5v3"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
      />
    </svg>
  );
}

function UsersIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M9 10.2a2.3 2.3 0 1 0 0-4.6 2.3 2.3 0 0 0 0 4.6Zm6.3-.8a1.9 1.9 0 1 0 0-3.8 1.9 1.9 0 0 0 0 3.8ZM4.8 18.2a4.2 4.2 0 0 1 8.4 0M13.1 18.2a3.2 3.2 0 0 1 6.4 0"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function ShieldCheckIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M12 3.8 18.8 6v5.2c0 4.4-2.6 7.3-6.8 8.9-4.2-1.6-6.8-4.5-6.8-8.9V6L12 3.8Zm-2.4 8.1 1.7 1.7 3.2-3.2"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function PromptIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M4.8 17.8h5.2M6.2 14.8l8.6-8.6 2.8 2.8-8.6 8.6-3.6.8.8-3.6Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function TraceIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M5.5 6.5h3M15.5 17.5h3M6.9 6.5c1.1 0 2 .9 2 2s.9 2 2 2h2.2c1.1 0 2 .9 2 2s.9 2 2 2"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
      />
      <circle cx="5.5" cy="6.5" r="1.3" fill="currentColor" />
      <circle cx="18.5" cy="17.5" r="1.3" fill="currentColor" />
    </svg>
  );
}

function SearchIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <circle cx="10.3" cy="10.3" r="4.8" fill="none" stroke="currentColor" strokeWidth="1.7" />
      <path d="M14 14 19 19" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" />
    </svg>
  );
}

function GridIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M5.5 5.5h5v5h-5zM13.5 5.5h5v5h-5zM5.5 13.5h5v5h-5zM13.5 13.5h5v5h-5z"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
      />
    </svg>
  );
}

function DriftIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M3.5 13.2h2.8l2-4.5 3.1 8 2.7-6 1.7 2.5h4.7"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function JudgeIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M6 8.2h12M12 8.2v9.8M7.5 8.2l-2.6 4h5.2l-2.6-4Zm9 0-2.6 4h5.2l-2.6-4ZM8.5 18.2h7"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function StackIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M4.8 7.2 12 4.2l7.2 3-7.2 3-7.2-3Zm0 5L12 9.2l7.2 3-7.2 3-7.2-3Zm0 5L12 14.2l7.2 3-7.2 3-7.2-3Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function NeuralIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M6.5 7.5h4l2.8 3h4.2M6.5 16.5h4l2.8-3h4.2M10.5 7.5v9"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
      />
      <circle cx="6.5" cy="7.5" r="1.3" fill="currentColor" />
      <circle cx="6.5" cy="16.5" r="1.3" fill="currentColor" />
      <circle cx="17.5" cy="10.5" r="1.3" fill="currentColor" />
      <circle cx="17.5" cy="13.5" r="1.3" fill="currentColor" />
    </svg>
  );
}

function SentinelIcon() {
  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M12 4.4a4 4 0 0 1 4 4v2.1c0 1 .3 1.9.9 2.7l.7 1h-11l.7-1c.6-.8.9-1.7.9-2.7V8.4a4 4 0 0 1 4-4Zm-1.8 12.7a1.8 1.8 0 0 0 3.6 0"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function ProjectMicroFedIcon({ projectId, kind }: { projectId: string; kind: IntegrationKind }) {
  switch (projectId) {
    case "config-forge":
      return <SlidersIcon />;
    case "interview-os":
      return <UsersIcon />;
    case "context-watchdog":
      return <ShieldCheckIcon />;
    case "prompt-ops":
      return <PromptIcon />;
    case "agent-tracer":
      return <TraceIcon />;
    case "agentic-research-assistant":
      return <SearchIcon />;
    case "agentic-ui":
      return <GridIcon />;
    case "drift-watch":
      return <DriftIcon />;
    case "llm-judge":
      return <JudgeIcon />;
    case "ragbench":
      return <StackIcon />;
    case "neuralscope":
      return <NeuralIcon />;
    case "mlops-sentinel":
      return <SentinelIcon />;
    default:
      return <ProjectKindIcon kind={kind} />;
  }
}

function ProjectKindIcon({ kind }: { kind: IntegrationKind }) {
  if (kind === "storybook") {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
        <path
          d="M6 5.5h12v13H6zM9.2 9h5.6M9.2 12h5.6M9.2 15h3.6"
          fill="none"
          stroke="currentColor"
          strokeWidth="1.7"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </svg>
    );
  }

  if (kind === "documentation") {
    return (
      <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
        <path
          d="M7 4.5h8l3 3V19.5H7zM15 4.5v3h3"
          fill="none"
          stroke="currentColor"
          strokeWidth="1.7"
          strokeLinejoin="round"
        />
      </svg>
    );
  }

  return (
    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
      <path
        d="M3.8 6.8h16.4v10.4H3.8zM8 17.2v2M16 17.2v2"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.7"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

/**
 * Layout shell that mirrors partner-portal host behavior with global nav + content frame.
 */
export function ShellLayout({
  projects,
  activeProjectId,
  totalProjects,
  currentRole,
  onRoleChange,
  currentTheme,
  onThemeToggle,
  children
}: PropsWithChildren<ShellLayoutProps>) {
  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);
  const rolePickerRef = useRef<HTMLSelectElement | null>(null);
  const categorizedProjects = groupProjectsByCategory(projects);
  const categoryOrder = ["platform", "agentics", "observability"];
  const activeProject = projects.find((project) => project.id === activeProjectId);

  function handleUserSettingsClick() {
    if (isSidebarCollapsed) {
      setIsSidebarCollapsed(false);
      window.setTimeout(() => {
        rolePickerRef.current?.focus();
      }, 130);
      return;
    }

    rolePickerRef.current?.focus();
  }

  return (
    <div className="shell-root">
      <header className="shell-header">
        <div className="shell-header-brand">
          <p className="eyebrow">AstraMesh Federation Host</p>
          <h1>AstraMesh</h1>
          <p className="header-subtitle">One secure mesh for your AI app fleet.</p>
        </div>

        <div className="shell-header-meta">
          <div className="header-status-line" aria-label="Project totals">
            <span>{projects.length}/{totalProjects} modules visible</span>
            <span>Route-based workspace</span>
            <span>Production-safe embedding</span>
          </div>

          <button
            type="button"
            className={
              currentTheme === "dark" ? "theme-switch header-theme-switch dark" : "theme-switch header-theme-switch"
            }
            onClick={onThemeToggle}
            aria-pressed={currentTheme === "dark"}
            aria-label={
              currentTheme === "light" ? "Switch to dark theme" : "Switch to light theme"
            }
          >
            <span className="theme-switch-track" aria-hidden="true">
              <span className="theme-switch-thumb">
                {currentTheme === "dark" ? <ThemeMoonIcon /> : <ThemeSunIcon />}
              </span>
            </span>
          </button>
        </div>
      </header>

      <div className={isSidebarCollapsed ? "shell-body sidebar-collapsed" : "shell-body"}>
        <div className={isSidebarCollapsed ? "shell-left-rail collapsed" : "shell-left-rail"}>
          <aside className="shell-sidebar" aria-label="Project navigation">
            <div className="shell-sidebar-topbar">
              <span className="shell-sidebar-topbar-title">Micro Feds</span>
              <button
                type="button"
                className="shell-sidebar-toggle"
                onClick={() => setIsSidebarCollapsed((previousValue) => !previousValue)}
                aria-label={isSidebarCollapsed ? "Expand sidebar" : "Collapse sidebar"}
                aria-pressed={isSidebarCollapsed}
              >
                <span aria-hidden="true">
                  {isSidebarCollapsed ? <ChevronRightIcon /> : <ChevronLeftIcon />}
                </span>
              </button>
            </div>

            <nav className="shell-sidebar-nav">
              <Link className="side-link side-link-home" to="/dashboard" title="AstraMesh Overview">
                <span className="side-link-icon" aria-hidden="true">
                  <HomeIcon />
                </span>
                <span className="side-link-text">AstraMesh Overview</span>
              </Link>

              {categoryOrder.map((category) => {
                const items = categorizedProjects[category] ?? [];
                if (items.length === 0) {
                  return null;
                }

                return (
                  <section key={category} className="side-section">
                    <h2>{category}</h2>
                    <ul>
                      {items.map((project) => {
                        const isActive = project.id === activeProjectId;
                        return (
                          <li key={project.id}>
                            <Link
                              className={isActive ? "side-link active" : "side-link"}
                              to={`/workspace/${project.id}`}
                              title={project.name}
                            >
                              <span className="side-link-icon" aria-hidden="true">
                                <ProjectMicroFedIcon projectId={project.id} kind={project.kind} />
                              </span>
                              <span className="side-link-text">{project.name}</span>
                            </Link>
                          </li>
                        );
                      })}
                    </ul>
                  </section>
                );
              })}
            </nav>
          </aside>

          <section className="shell-user-settings" aria-label="User profile settings">
            <div className="sidebar-user-header">
              <button
                type="button"
                className="sidebar-user-avatar-button"
                onClick={handleUserSettingsClick}
                aria-label={
                  isSidebarCollapsed ? "Open user settings" : "Focus user role settings"
                }
                title={isSidebarCollapsed ? "Open user settings" : "User settings"}
              >
                <span className="sidebar-user-avatar" aria-hidden="true">
                  <UserIcon />
                </span>
              </button>
              <div className="sidebar-user-copy">
                <p className="sidebar-user-eyebrow">User Profile Settings</p>
                <p className="sidebar-user-name">AstraMesh Operator</p>
              </div>
            </div>

            <label className="role-picker sidebar-role-picker" htmlFor="role-picker">
              <span>Access Role</span>
              <select
                id="role-picker"
                ref={rolePickerRef}
                value={currentRole}
                onChange={(event) => onRoleChange(event.target.value as UserRole)}
              >
                {ROLE_OPTIONS.map((role) => (
                  <option key={role.value} value={role.value}>
                    {role.label}
                  </option>
                ))}
              </select>
            </label>
          </section>
        </div>

        <main id="main-content" className="shell-main">
          {children}
        </main>
      </div>

      <AgentChatDock activeModuleName={activeProject?.name} />
    </div>
  );
}
