// Generated by GitHub Copilot
import { Link } from "react-router-dom";
import type { PropsWithChildren } from "react";
import { ROLE_OPTIONS } from "../utils/access";
import type { ProjectIntegration, UserRole } from "../types";

interface ShellLayoutProps {
  projects: ProjectIntegration[];
  activeProjectId?: string;
  totalProjects: number;
  currentRole: UserRole;
  onRoleChange: (nextRole: UserRole) => void;
}

/**
 * Groups projects by category so the side navigation stays scannable at scale.
 */
function groupProjectsByCategory(
  projects: ProjectIntegration[]
): Record<string, ProjectIntegration[]> {
  return projects.reduce<Record<string, ProjectIntegration[]>>((accumulator, project) => {
    if (!accumulator[project.category]) {
      accumulator[project.category] = [];
    }
    accumulator[project.category].push(project);
    return accumulator;
  }, {});
}

/**
 * Layout shell that mirrors partner-portal host behavior with global nav + content frame.
 */
export function ShellLayout({
  projects,
  activeProjectId,
  totalProjects,
  currentRole,
  onRoleChange,
  children
}: PropsWithChildren<ShellLayoutProps>) {
  const categorizedProjects = groupProjectsByCategory(projects);
  const categoryOrder = ["platform", "agentics", "observability"];

  return (
    <div className="shell-root">
      <header className="shell-header">
        <div>
          <p className="eyebrow">AstraMesh Federation Host</p>
          <h1>AstraMesh</h1>
          <p className="header-subtitle">One secure mesh for your AI app fleet.</p>
        </div>
        <div className="header-stats" aria-label="Project totals">
          <label className="role-picker" htmlFor="role-picker">
            <span>Access Role</span>
            <select
              id="role-picker"
              value={currentRole}
              onChange={(event) => onRoleChange(event.target.value as UserRole)}
            >
              {ROLE_OPTIONS.map((role) => (
                <option key={role.value} value={role.value}>
                  {role.label}
                </option>
              ))}
            </select>
          </label>
          <span>{projects.length}/{totalProjects} modules visible</span>
          <span>Route-based workspace</span>
          <span>Production-safe embedding</span>
        </div>
      </header>

      <div className="shell-body">
        <aside className="shell-sidebar" aria-label="Project navigation">
          <nav>
            <Link className="side-link side-link-home" to="/dashboard">
              AstraMesh Overview
            </Link>

            {categoryOrder.map((category) => {
              const items = categorizedProjects[category] ?? [];
              if (items.length === 0) {
                return null;
              }

              return (
                <section key={category} className="side-section">
                  <h2>{category}</h2>
                  <ul>
                    {items.map((project) => {
                      const isActive = project.id === activeProjectId;
                      return (
                        <li key={project.id}>
                          <Link
                            className={isActive ? "side-link active" : "side-link"}
                            to={`/workspace/${project.id}`}
                          >
                            {project.name}
                          </Link>
                        </li>
                      );
                    })}
                  </ul>
                </section>
              );
            })}
          </nav>
        </aside>

        <main id="main-content" className="shell-main">
          {children}
        </main>
      </div>
    </div>
  );
}
