// Generated by GitHub Copilot
import { useCallback, useEffect, useMemo, useState } from "react";
import type { ProjectIntegration } from "../types";
import { normalizeProjectUrl } from "../utils/url";

interface WorkspaceFrameProps {
  project: ProjectIntegration;
}

type HealthState = "checking" | "online" | "offline" | "unknown";

interface ProbeResponse {
  state?: string;
}

function resolveControlPlaneBaseUrl(): string {
  const configuredUrl = import.meta.env.VITE_CONTROL_PLANE_URL?.trim();
  if (!configuredUrl) {
    return "/control-plane";
  }

  return configuredUrl.replace(/\/$/, "");
}

const CONTROL_PLANE_BASE_URL = resolveControlPlaneBaseUrl();

/**
 * Tests project endpoint health and returns unknown if browser policy blocks verification.
 */
async function checkReachabilityDirect(targetUrl: string): Promise<HealthState> {
  const timeoutController = new AbortController();
  const timer = window.setTimeout(() => timeoutController.abort(), 3500);
  try {
    const response = await fetch(targetUrl, {
      method: "GET",
      cache: "no-store",
      signal: timeoutController.signal
    });
    return response.ok ? "online" : "offline";
  } catch {
    return "unknown";
  } finally {
    window.clearTimeout(timer);
  }
}

/**
 * Uses control-plane backend to probe target health without browser CORS limitations.
 */
async function checkReachability(targetUrl: string): Promise<HealthState> {
  const timeoutController = new AbortController();
  const timer = window.setTimeout(() => timeoutController.abort(), 5000);
  const probeUrl = `${CONTROL_PLANE_BASE_URL}/api/health/probe?url=${encodeURIComponent(targetUrl)}`;

  try {
    const response = await fetch(probeUrl, {
      method: "GET",
      cache: "no-store",
      signal: timeoutController.signal
    });

    if (!response.ok) {
      if (response.status === 400 || response.status === 403) {
        return "unknown";
      }

      return checkReachabilityDirect(targetUrl);
    }

    const payload = (await response.json()) as ProbeResponse;
    if (payload.state === "online" || payload.state === "offline" || payload.state === "unknown") {
      return payload.state;
    }

    return "unknown";
  } catch {
    return checkReachabilityDirect(targetUrl);
  } finally {
    window.clearTimeout(timer);
  }
}

/**
 * Workspace panel that embeds project UIs and provides secure launch + operational hints.
 */
export function WorkspaceFrame({ project }: WorkspaceFrameProps) {
  const [health, setHealth] = useState<HealthState>("checking");
  const [lastCheckedAt, setLastCheckedAt] = useState<string | null>(null);
  const isExternalProject = project.launchMode === "external";

  const safeUrl = useMemo(() => normalizeProjectUrl(project.url), [project.url]);
  const safeHealthUrl = useMemo(
    () => (project.healthUrl ? normalizeProjectUrl(project.healthUrl) : null),
    [project.healthUrl]
  );

  const refreshHealth = useCallback(async () => {
    if (isExternalProject) {
      setHealth("online");
      setLastCheckedAt(new Date().toISOString());
      return;
    }

    if (!project.healthUrl) {
      setHealth("unknown");
      setLastCheckedAt(new Date().toISOString());
      return;
    }

    if (!safeHealthUrl) {
      setHealth("offline");
      setLastCheckedAt(new Date().toISOString());
      return;
    }

    setHealth("checking");
    const nextHealth = await checkReachability(safeHealthUrl);
    setHealth(nextHealth);
    setLastCheckedAt(new Date().toISOString());
  }, [isExternalProject, project.healthUrl, safeHealthUrl]);

  useEffect(() => {
    let isMounted = true;
    void refreshHealth();
    const timer = window.setInterval(() => {
      if (isMounted) {
        void refreshHealth();
      }
    }, 30000);

    return () => {
      isMounted = false;
      window.clearInterval(timer);
    };
  }, [refreshHealth]);

  if (!safeUrl) {
    return (
      <section className="workspace-panel" aria-live="polite">
        <h2>{project.name}</h2>
        <p>
          Blocked by production URL policy. Check module URL and
          `VITE_ALLOWED_IFRAME_ORIGINS` configuration.
        </p>
      </section>
    );
  }

  const healthClass = isExternalProject ? "health-pill health-online" : `health-pill health-${health}`;

  return (
    <section className="workspace-panel" aria-labelledby="workspace-title">
      <header className="workspace-header">
        <div>
          <h2 id="workspace-title">{project.name}</h2>
          <p>{project.tagline}</p>
        </div>
        <div className="workspace-actions">
          {isExternalProject ? <span className={healthClass}>external</span> : null}
          {!isExternalProject ? <span className={healthClass}>{health}</span> : null}
          {!isExternalProject ? (
            <button type="button" onClick={() => void refreshHealth()}>
              Retry health check
            </button>
          ) : null}
          <a href={safeUrl} target="_blank" rel="noreferrer">
            Open in new tab
          </a>
        </div>
      </header>

      <div className="workspace-meta">
        <p>
          <strong>Repo:</strong> {project.repoPath}
        </p>
        <p>
          <strong>Start:</strong> {project.startCommand}
        </p>
        <p>
          <strong>Checked:</strong>{" "}
          {lastCheckedAt
            ? new Date(lastCheckedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })
            : "Not checked yet"}
        </p>
      </div>

      {project.launchMode === "external" ? (
        <div className="external-panel">
          <p>
            This integration opens as external docs/runtime. Use the button above to launch it in a
            dedicated tab.
          </p>
        </div>
      ) : health === "offline" ? (
        <div className="external-panel" role="status">
          <p>
            Module appears offline, so the embedded frame is hidden. Start the service with the
            command above and retry health check.
          </p>
        </div>
      ) : (
        <iframe
          className="workspace-iframe"
          title={`${project.name} workspace`}
          src={safeUrl}
          loading="lazy"
          sandbox="allow-forms allow-modals allow-pointer-lock allow-popups allow-same-origin allow-scripts"
          referrerPolicy="no-referrer"
        />
      )}

      {health === "offline" && !isExternalProject ? (
        <p className="offline-hint" role="status">
          Module appears offline. The backend or frontend service may be down. Start it with the
          command shown above, then refresh this route.
        </p>
      ) : null}

      {health === "unknown" && !isExternalProject ? (
        <p className="offline-hint" role="status">
          Health could not be verified. Ensure the control-plane backend is running and CORS
          allowlist includes the shell origin.
        </p>
      ) : null}
    </section>
  );
}
