// Generated by GitHub Copilot
import { useEffect, useMemo, useState } from "react";
import type { ProjectIntegration } from "../types";
import { normalizeProjectUrl } from "../utils/url";

interface WorkspaceFrameProps {
  project: ProjectIntegration;
}

type HealthState = "checking" | "online" | "offline";

/**
 * Tests whether a project endpoint is reachable without relying on permissive CORS.
 */
async function checkReachability(targetUrl: string): Promise<boolean> {
  const timeoutController = new AbortController();
  const timer = window.setTimeout(() => timeoutController.abort(), 3500);
  try {
    await fetch(targetUrl, { method: "GET", mode: "no-cors", signal: timeoutController.signal });
    return true;
  } catch {
    return false;
  } finally {
    window.clearTimeout(timer);
  }
}

/**
 * Workspace panel that embeds project UIs and provides secure launch + operational hints.
 */
export function WorkspaceFrame({ project }: WorkspaceFrameProps) {
  const [health, setHealth] = useState<HealthState>("checking");

  const safeUrl = useMemo(() => normalizeProjectUrl(project.url), [project.url]);
  const safeHealthUrl = useMemo(
    () => (project.healthUrl ? normalizeProjectUrl(project.healthUrl) : null),
    [project.healthUrl]
  );

  useEffect(() => {
    let isMounted = true;

    /**
     * Performs immediate and interval reachability checks to keep status current.
     */
    async function refreshHealth() {
      if (!project.healthUrl) {
        if (isMounted) {
          setHealth("online");
        }
        return;
      }

      if (!safeHealthUrl) {
        if (isMounted) {
          setHealth("offline");
        }
        return;
      }

      const isOnline = await checkReachability(safeHealthUrl);
      if (isMounted) {
        setHealth(isOnline ? "online" : "offline");
      }
    }

    void refreshHealth();
    const timer = window.setInterval(() => {
      void refreshHealth();
    }, 30000);

    return () => {
      isMounted = false;
      window.clearInterval(timer);
    };
  }, [project.healthUrl, safeHealthUrl]);

  if (!safeUrl) {
    return (
      <section className="workspace-panel" aria-live="polite">
        <h2>{project.name}</h2>
        <p>
          Blocked by production URL policy. Check module URL and
          `VITE_ALLOWED_IFRAME_ORIGINS` configuration.
        </p>
      </section>
    );
  }

  const healthClass = `health-pill health-${health}`;

  return (
    <section className="workspace-panel" aria-labelledby="workspace-title">
      <header className="workspace-header">
        <div>
          <h2 id="workspace-title">{project.name}</h2>
          <p>{project.tagline}</p>
        </div>
        <div className="workspace-actions">
          <span className={healthClass}>{health}</span>
          <a href={safeUrl} target="_blank" rel="noreferrer">
            Open in new tab
          </a>
        </div>
      </header>

      <div className="workspace-meta">
        <p>
          <strong>Repo:</strong> {project.repoPath}
        </p>
        <p>
          <strong>Start:</strong> {project.startCommand}
        </p>
      </div>

      {project.launchMode === "external" ? (
        <div className="external-panel">
          <p>
            This integration opens as external docs/runtime. Use the button above to launch it in a
            dedicated tab.
          </p>
        </div>
      ) : (
        <iframe
          className="workspace-iframe"
          title={`${project.name} workspace`}
          src={safeUrl}
          loading="lazy"
          sandbox="allow-forms allow-modals allow-pointer-lock allow-popups allow-same-origin allow-scripts"
          referrerPolicy="no-referrer"
        />
      )}

      {health === "offline" ? (
        <p className="offline-hint" role="status">
          Module appears offline. Start it with the command shown above, then refresh this route.
        </p>
      ) : null}
    </section>
  );
}
