// Generated by GitHub Copilot
import { BrowserRouter, Navigate, Route, Routes, useLocation, useParams } from "react-router-dom";
import { ProjectCards } from "./components/ProjectCards";
import { ShellLayout } from "./components/ShellLayout";
import { WorkspaceFrame } from "./components/WorkspaceFrame";
import { PROJECTS } from "./data/projects";

/**
 * Route wrapper resolves the selected project from URL params and renders the workspace frame.
 */
function WorkspaceRoute() {
  const routeParams = useParams<{ projectId: string }>();
  const selectedProject = PROJECTS.find((project) => project.id === routeParams.projectId);

  if (!selectedProject) {
    return <Navigate to="/dashboard" replace />;
  }

  return <WorkspaceFrame project={selectedProject} />;
}

/**
 * Shell-aware router keeps sidebar state in sync with the current route.
 */
function AppRoutes() {
  const location = useLocation();
  const routeProjectMatch = location.pathname.match(/^\/workspace\/([a-z0-9-]+)/i);
  const activeProjectId = routeProjectMatch ? routeProjectMatch[1] : undefined;

  return (
    <ShellLayout projects={PROJECTS} activeProjectId={activeProjectId}>
      <Routes>
        <Route path="/" element={<Navigate to="/dashboard" replace />} />
        <Route path="/dashboard" element={<ProjectCards projects={PROJECTS} />} />
        <Route path="/workspace/:projectId" element={<WorkspaceRoute />} />
        <Route path="*" element={<Navigate to="/dashboard" replace />} />
      </Routes>
    </ShellLayout>
  );
}

/**
 * App root composes global router and skip navigation for keyboard users.
 */
export default function App() {
  return (
    <BrowserRouter>
      <a className="skip-link" href="#main-content">
        Skip to main content
      </a>
      <AppRoutes />
    </BrowserRouter>
  );
}
