// Generated by GitHub Copilot
import { useMemo, useState } from "react";
import { BrowserRouter, Navigate, Route, Routes, useLocation, useParams } from "react-router-dom";
import { ProjectCards } from "./components/ProjectCards";
import { ShellLayout } from "./components/ShellLayout";
import { WorkspaceFrame } from "./components/WorkspaceFrame";
import { PROJECTS } from "./data/projects";
import type { ProjectIntegration, UserRole } from "./types";
import { filterProjectsByRole, getStoredRole, setStoredRole } from "./utils/access";

/**
 * Route wrapper resolves the selected project from URL params and renders the workspace frame.
 */
function WorkspaceRoute({ projects }: { projects: ProjectIntegration[] }) {
  const routeParams = useParams<{ projectId: string }>();
  const selectedProject = projects.find((project) => project.id === routeParams.projectId);

  if (!selectedProject) {
    return <Navigate to="/dashboard" replace />;
  }

  return <WorkspaceFrame project={selectedProject} />;
}

/**
 * Shell-aware router keeps sidebar state in sync with the current route.
 */
function AppRoutes({
  projects,
  currentRole,
  onRoleChange,
  totalProjects
}: {
  projects: ProjectIntegration[];
  currentRole: UserRole;
  onRoleChange: (nextRole: UserRole) => void;
  totalProjects: number;
}) {
  const location = useLocation();
  const routeProjectMatch = location.pathname.match(/^\/workspace\/([a-z0-9-]+)/i);
  const activeProjectId = routeProjectMatch ? routeProjectMatch[1] : undefined;

  return (
    <ShellLayout
      projects={projects}
      activeProjectId={activeProjectId}
      currentRole={currentRole}
      onRoleChange={onRoleChange}
      totalProjects={totalProjects}
    >
      <Routes>
        <Route path="/" element={<Navigate to="/dashboard" replace />} />
        <Route path="/dashboard" element={<ProjectCards projects={projects} />} />
        <Route path="/workspace/:projectId" element={<WorkspaceRoute projects={projects} />} />
        <Route path="*" element={<Navigate to="/dashboard" replace />} />
      </Routes>
    </ShellLayout>
  );
}

/**
 * App root composes global router and skip navigation for keyboard users.
 */
export default function App() {
  const [activeRole, setActiveRole] = useState<UserRole>(() => getStoredRole());

  const visibleProjects = useMemo(
    () => filterProjectsByRole(PROJECTS, activeRole),
    [activeRole]
  );

  function handleRoleChange(nextRole: UserRole) {
    setActiveRole(nextRole);
    setStoredRole(nextRole);
  }

  return (
    <BrowserRouter>
      <a className="skip-link" href="#main-content">
        Skip to main content
      </a>
      <AppRoutes
        projects={visibleProjects}
        currentRole={activeRole}
        onRoleChange={handleRoleChange}
        totalProjects={PROJECTS.length}
      />
    </BrowserRouter>
  );
}
