// Generated by GitHub Copilot

export type IntegrationKind = "frontend" | "storybook" | "documentation";

export type LaunchMode = "iframe" | "external";

export type ThemeMode = "light" | "dark";

export type UserRole = "admin" | "platform-ops" | "ml-ops" | "research" | "viewer";

export interface ProjectIntegration {
  id: string;
  name: string;
  tagline: string;
  category: "platform" | "agentics" | "observability";
  kind: IntegrationKind;
  launchMode: LaunchMode;
  url: string;
  healthUrl?: string;
  startCommand: string;
  repoPath: string;
  statusNote: string;
  allowedRoles: UserRole[];
}
