// Generated by GitHub Copilot

export type IntegrationKind = "frontend" | "storybook" | "documentation";

export type LaunchMode = "iframe" | "external";

export interface ProjectIntegration {
  id: string;
  name: string;
  tagline: string;
  category: "platform" | "agentics" | "observability";
  kind: IntegrationKind;
  launchMode: LaunchMode;
  url: string;
  healthUrl?: string;
  startCommand: string;
  repoPath: string;
  statusNote: string;
}
