// Generated by GitHub Copilot
/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_BASE_PATH?: string;
  readonly VITE_ALLOWED_IFRAME_ORIGINS?: string;
  readonly VITE_DEFAULT_USER_ROLE?: string;
  readonly VITE_DEFAULT_THEME?: string;
  readonly VITE_CONTROL_PLANE_URL?: string;
  readonly VITE_DRIFT_WATCH_URL?: string;
  readonly VITE_LLM_JUDGE_URL?: string;
  readonly VITE_RAGBENCH_URL?: string;
  readonly VITE_PROMPT_OPS_URL?: string;
  readonly VITE_NEURALSCOPE_URL?: string;
  readonly VITE_CONFIG_FORGE_URL?: string;
  readonly VITE_INTERVIEW_OS_URL?: string;
  readonly VITE_MLOPS_SENTINEL_URL?: string;
  readonly VITE_AGENT_TRACER_URL?: string;
  readonly VITE_AGENTIC_RESEARCH_ASSISTANT_URL?: string;
  readonly VITE_AGENTIC_UI_URL?: string;
  readonly VITE_CONTEXT_WATCHDOG_URL?: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
