// Generated by GitHub Copilot
import cors from "cors";
import express, { type NextFunction, type Request, type Response } from "express";
import rateLimit from "express-rate-limit";
import { randomUUID } from "node:crypto";
import { resolveControlPlaneConfig, type ControlPlaneConfig } from "./config.js";
import { ModuleRegistry } from "./registry.js";
import { evaluateModuleStatus } from "./scoring.js";
import { DEFAULT_MODULE_CONTRACTS } from "./seeds.js";
import { parseModuleContractPayload, parseTelemetryPayload } from "./validation.js";

export interface ControlPlaneAppContext {
  app: express.Express;
  registry: ModuleRegistry;
  config: ControlPlaneConfig;
}

function isAllowedOrigin(origin: string | undefined, allowedOrigins: string[]): boolean {
  if (!origin) {
    return true;
  }

  return allowedOrigins.includes(origin);
}

function isLocalHostname(hostname: string): boolean {
  const normalized = hostname.trim().toLowerCase();
  return normalized === "localhost" || normalized === "127.0.0.1" || normalized === "::1";
}

function isProbeTargetAllowed(targetUrl: URL, allowedProbeOrigins: string[]): boolean {
  if (targetUrl.protocol !== "http:" && targetUrl.protocol !== "https:") {
    return false;
  }

  if (isLocalHostname(targetUrl.hostname)) {
    return true;
  }

  return allowedProbeOrigins.includes(targetUrl.origin);
}

async function probeTargetHealth(
  targetUrl: string,
  timeoutMs: number
): Promise<{ state: "online" | "offline" | "unknown"; httpStatus: number | null; error?: string; durationMs: number }> {
  const started = process.hrtime.bigint();
  const timeoutController = new AbortController();
  const timer = setTimeout(() => timeoutController.abort(), timeoutMs);

  try {
    const response = await fetch(targetUrl, {
      method: "GET",
      signal: timeoutController.signal,
      redirect: "follow"
    });

    const durationMs = Number(process.hrtime.bigint() - started) / 1_000_000;
    return {
      state: response.ok ? "online" : "offline",
      httpStatus: response.status,
      durationMs: Number(durationMs.toFixed(2))
    };
  } catch (error) {
    const durationMs = Number(process.hrtime.bigint() - started) / 1_000_000;
    return {
      state: "unknown",
      httpStatus: null,
      error: error instanceof Error ? error.message : "Probe failed",
      durationMs: Number(durationMs.toFixed(2))
    };
  } finally {
    clearTimeout(timer);
  }
}

function buildStatusSnapshot(registry: ModuleRegistry) {
  const statuses = registry
    .listModules()
    .map((moduleRecord) =>
      evaluateModuleStatus(moduleRecord, registry.missingDependencies(moduleRecord))
    )
    .sort((left, right) => left.score - right.score);

  const summary = {
    healthy: statuses.filter((status) => status.state === "healthy").length,
    degraded: statuses.filter((status) => status.state === "degraded").length,
    critical: statuses.filter((status) => status.state === "critical").length,
    unknown: statuses.filter((status) => status.state === "unknown").length
  };

  return { statuses, summary };
}

function requestIdMiddleware(request: Request, response: Response, next: NextFunction): void {
  const incomingRequestId = request.header("x-request-id");
  const requestId = incomingRequestId && incomingRequestId.trim().length > 0
    ? incomingRequestId.trim()
    : randomUUID();

  request.requestId = requestId;
  response.setHeader("x-request-id", requestId);
  next();
}

function requestLogMiddleware(request: Request, response: Response, next: NextFunction): void {
  const started = process.hrtime.bigint();

  response.on("finish", () => {
    const elapsedMs = Number(process.hrtime.bigint() - started) / 1_000_000;

    console.info(
      JSON.stringify({
        level: "info",
        message: "request.completed",
        requestId: request.requestId,
        method: request.method,
        path: request.path,
        statusCode: response.statusCode,
        durationMs: Number(elapsedMs.toFixed(2)),
        origin: request.headers.origin ?? null,
        timestamp: new Date().toISOString()
      })
    );
  });

  next();
}

export function createControlPlaneApp(
  overrides: Partial<ControlPlaneConfig> = {}
): ControlPlaneAppContext {
  const config = resolveControlPlaneConfig(overrides);
  const registry = new ModuleRegistry();

  if (config.seedDefaults) {
    for (const moduleContract of DEFAULT_MODULE_CONTRACTS) {
      registry.upsertContract(moduleContract);
    }
  }

  const app = express();
  app.disable("x-powered-by");

  app.use(express.json({ limit: "1mb" }));
  app.use(requestIdMiddleware);
  app.use(requestLogMiddleware);

  app.use(
    cors({
      origin: (origin, callback) => {
        if (isAllowedOrigin(origin, config.allowedOrigins)) {
          callback(null, true);
          return;
        }

        callback(new Error(`Origin ${origin ?? "unknown"} is not allowed.`));
      },
      credentials: true
    })
  );

  app.use(
    rateLimit({
      windowMs: 60_000,
      limit: config.requestRateLimitPerMinute,
      standardHeaders: true,
      legacyHeaders: false,
      message: {
        error: "Rate limit exceeded. Retry after one minute."
      }
    })
  );

  app.get("/health", (_request, response) => {
    response.json({
      status: "ok",
      service: config.serviceName,
      version: config.version,
      uptimeSec: Math.round(process.uptime()),
      time: new Date().toISOString()
    });
  });

  app.get("/ready", (_request, response) => {
    const { summary } = buildStatusSnapshot(registry);
    const isReady = summary.critical === 0;

    response.status(isReady ? 200 : 503).json({
      status: isReady ? "ready" : "degraded",
      modulesTracked: registry.count(),
      criticalModules: summary.critical,
      unknownModules: summary.unknown,
      evaluatedAt: new Date().toISOString()
    });
  });

  app.get("/api/config", (_request, response) => {
    response.json({
      service: config.serviceName,
      version: config.version,
      requestRateLimitPerMinute: config.requestRateLimitPerMinute,
      probeTimeoutMs: config.probeTimeoutMs,
      allowedOrigins: config.allowedOrigins,
      allowedProbeOrigins: config.allowedProbeOrigins,
      seedDefaults: config.seedDefaults
    });
  });

  app.get("/api/modules", (_request, response) => {
    response.json({
      modules: registry.listModules(),
      total: registry.count()
    });
  });

  app.post("/api/modules/register", (request, response) => {
    const parsedContract = parseModuleContractPayload(request.body);
    if (!parsedContract.ok) {
      response.status(400).json({
        error: parsedContract.error,
        requestId: request.requestId
      });
      return;
    }

    const wasExisting = Boolean(registry.getModule(parsedContract.value.id));
    const savedModule = registry.upsertContract(parsedContract.value);

    response.status(wasExisting ? 200 : 201).json({
      message: wasExisting
        ? "Module contract updated."
        : "Module contract registered.",
      module: savedModule
    });
  });

  app.post("/api/modules/:moduleId/telemetry", (request, response) => {
    const parsedTelemetry = parseTelemetryPayload(request.body);
    if (!parsedTelemetry.ok) {
      response.status(400).json({
        error: parsedTelemetry.error,
        requestId: request.requestId
      });
      return;
    }

    const updatedRecord = registry.updateTelemetry(request.params.moduleId, parsedTelemetry.value);
    if (!updatedRecord) {
      response.status(404).json({
        error: `Unknown module id: ${request.params.moduleId}`,
        requestId: request.requestId
      });
      return;
    }

    response.json({
      message: "Telemetry ingested.",
      module: updatedRecord
    });
  });

  app.get("/api/modules/status", (_request, response) => {
    const { statuses, summary } = buildStatusSnapshot(registry);

    response.json({
      statuses,
      summary,
      generatedAt: new Date().toISOString()
    });
  });

  app.get("/api/health/probe", async (request, response) => {
    const rawTargetUrl = typeof request.query.url === "string" ? request.query.url.trim() : "";
    if (!rawTargetUrl) {
      response.status(400).json({
        error: "Query parameter 'url' is required.",
        requestId: request.requestId
      });
      return;
    }

    let parsedTargetUrl: URL;
    try {
      parsedTargetUrl = new URL(rawTargetUrl);
    } catch {
      response.status(400).json({
        error: "Query parameter 'url' must be a valid URL.",
        requestId: request.requestId
      });
      return;
    }

    if (!isProbeTargetAllowed(parsedTargetUrl, config.allowedProbeOrigins)) {
      response.status(403).json({
        error: `Probe target origin ${parsedTargetUrl.origin} is not allowed.`,
        requestId: request.requestId
      });
      return;
    }

    const probe = await probeTargetHealth(parsedTargetUrl.toString(), config.probeTimeoutMs);
    response.json({
      targetUrl: parsedTargetUrl.toString(),
      state: probe.state,
      httpStatus: probe.httpStatus,
      durationMs: probe.durationMs,
      error: probe.error,
      checkedAt: new Date().toISOString()
    });
  });

  app.get("/api/modules/:moduleId/status", (request, response) => {
    const moduleRecord = registry.getModule(request.params.moduleId);
    if (!moduleRecord) {
      response.status(404).json({
        error: `Unknown module id: ${request.params.moduleId}`,
        requestId: request.requestId
      });
      return;
    }

    response.json({
      status: evaluateModuleStatus(moduleRecord, registry.missingDependencies(moduleRecord))
    });
  });

  app.use((_request, response) => {
    response.status(404).json({
      error: "Route not found"
    });
  });

  app.use((error: Error, request: Request, response: Response, _next: NextFunction) => {
    const knownCorsError = error.message.includes("not allowed");
    const statusCode = knownCorsError ? 403 : 500;

    console.error(
      JSON.stringify({
        level: "error",
        message: "request.failed",
        requestId: request.requestId,
        statusCode,
        error: error.message,
        path: request.path,
        timestamp: new Date().toISOString()
      })
    );

    response.status(statusCode).json({
      error: knownCorsError ? "CORS origin rejected." : "Internal server error.",
      requestId: request.requestId
    });
  });

  return {
    app,
    registry,
    config
  };
}
