// Generated by GitHub Copilot
import { createServer } from "node:http";
import request from "supertest";
import { createControlPlaneApp } from "./app.js";

function createTestApp() {
  return createControlPlaneApp({
    seedDefaults: false,
    requestRateLimitPerMinute: 1000,
    allowedOrigins: ["http://localhost:4300"]
  }).app;
}

const baseModuleContract = {
  id: "model-hub",
  name: "Model Hub",
  category: "platform",
  baseUrl: "http://localhost:5420",
  healthUrl: "http://localhost:5420/health",
  ownerTeam: "platform-core",
  dependencies: [],
  slo: {
    availabilityPct: 99.9,
    latencyP95Ms: 300,
    errorRatePct: 0.5
  }
};

describe("control plane app", () => {
  it("returns liveness and readiness metadata", async () => {
    const app = createTestApp();

    const healthResponse = await request(app).get("/health");
    expect(healthResponse.status).toBe(200);
    expect(healthResponse.body.status).toBe("ok");
    expect(typeof healthResponse.headers["x-request-id"]).toBe("string");

    const readyResponse = await request(app).get("/ready");
    expect(readyResponse.status).toBe(200);
    expect(readyResponse.body.status).toBe("ready");
  });

  it("registers module contracts and returns unknown status before telemetry", async () => {
    const app = createTestApp();

    const registerResponse = await request(app)
      .post("/api/modules/register")
      .send(baseModuleContract);

    expect(registerResponse.status).toBe(201);
    expect(registerResponse.body.module.id).toBe("model-hub");

    const statusResponse = await request(app).get("/api/modules/status");
    expect(statusResponse.status).toBe(200);
    expect(statusResponse.body.statuses).toHaveLength(1);
    expect(statusResponse.body.statuses[0].state).toBe("unknown");
  });

  it("computes a healthy score when telemetry is within SLO", async () => {
    const app = createTestApp();

    await request(app)
      .post("/api/modules/register")
      .send(baseModuleContract)
      .expect(201);

    await request(app)
      .post("/api/modules/model-hub/telemetry")
      .send({
        availabilityPct: 99.95,
        latencyP95Ms: 220,
        errorRatePct: 0.2
      })
      .expect(200);

    const statusResponse = await request(app).get("/api/modules/model-hub/status");
    expect(statusResponse.status).toBe(200);
    expect(statusResponse.body.status.state).toBe("healthy");
    expect(statusResponse.body.status.score).toBeGreaterThanOrEqual(85);
  });

  it("computes a critical score when telemetry heavily breaches SLO", async () => {
    const app = createTestApp();

    await request(app)
      .post("/api/modules/register")
      .send(baseModuleContract)
      .expect(201);

    await request(app)
      .post("/api/modules/model-hub/telemetry")
      .send({
        availabilityPct: 93,
        latencyP95Ms: 1500,
        errorRatePct: 7
      })
      .expect(200);

    const statusResponse = await request(app).get("/api/modules/model-hub/status");
    expect(statusResponse.status).toBe(200);
    expect(statusResponse.body.status.state).toBe("critical");
    expect(statusResponse.body.status.reasons.length).toBeGreaterThan(0);
  });

  it("rejects malformed contract payloads", async () => {
    const app = createTestApp();

    const response = await request(app)
      .post("/api/modules/register")
      .send({
        id: "Model Hub",
        name: "",
        category: "platform",
        baseUrl: "javascript:alert('xss')"
      });

    expect(response.status).toBe(400);
    expect(typeof response.body.error).toBe("string");
  });

  it("blocks probe requests to disallowed public origins", async () => {
    const app = createTestApp();

    const response = await request(app)
      .get("/api/health/probe")
      .query({ url: "https://example.com/health" });

    expect(response.status).toBe(403);
    expect(String(response.body.error)).toContain("not allowed");
  });

  it("probes allowed localhost targets and reports online state", async () => {
    const app = createTestApp();

    const localService = createServer((requestMessage, responseMessage) => {
      if (requestMessage.url === "/health") {
        responseMessage.statusCode = 200;
        responseMessage.setHeader("content-type", "application/json");
        responseMessage.end(JSON.stringify({ ok: true }));
        return;
      }

      responseMessage.statusCode = 404;
      responseMessage.end();
    });

    const serverAddress = await new Promise<string>((resolve, reject) => {
      localService.listen(0, "127.0.0.1", () => {
        const boundAddress = localService.address();
        if (!boundAddress || typeof boundAddress === "string") {
          reject(new Error("Failed to resolve local server address."));
          return;
        }

        resolve(`http://127.0.0.1:${boundAddress.port}/health`);
      });
    });

    try {
      const response = await request(app)
        .get("/api/health/probe")
        .query({ url: serverAddress });

      expect(response.status).toBe(200);
      expect(response.body.state).toBe("online");
      expect(response.body.httpStatus).toBe(200);
    } finally {
      await new Promise<void>((resolve) => {
        localService.close(() => resolve());
      });
    }
  });
});
