// Generated by GitHub Copilot
import { createServer } from "node:http";
import request from "supertest";
import { createControlPlaneApp } from "./app.js";

function createTestApp() {
  return createControlPlaneApp({
    seedDefaults: false,
    requestRateLimitPerMinute: 1000,
    allowedOrigins: ["http://localhost:4300"]
  }).app;
}

const baseModuleContract = {
  id: "model-hub",
  name: "Model Hub",
  category: "platform",
  baseUrl: "http://localhost:5420",
  healthUrl: "http://localhost:5420/health",
  ownerTeam: "platform-core",
  dependencies: [],
  slo: {
    availabilityPct: 99.9,
    latencyP95Ms: 300,
    errorRatePct: 0.5
  }
};

async function waitForRunCompletion(app: ReturnType<typeof createTestApp>, runId: string) {
  const maxAttempts = 50;

  for (let attempt = 0; attempt < maxAttempts; attempt += 1) {
    const response = await request(app).get(`/api/orchestration/runs/${runId}`);
    expect(response.status).toBe(200);

    const status = response.body.run.status;
    if (status === "succeeded" || status === "failed" || status === "blocked" || status === "cancelled") {
      return response;
    }

    await new Promise((resolve) => {
      setTimeout(resolve, 20);
    });
  }

  throw new Error(`Timed out waiting for run ${runId} to complete.`);
}

async function createDelayedHealthServer(delayMs = 500) {
  const localService = createServer((_requestMessage, responseMessage) => {
    setTimeout(() => {
      responseMessage.statusCode = 200;
      responseMessage.setHeader("content-type", "application/json");
      responseMessage.end(JSON.stringify({ ok: true }));
    }, delayMs);
  });

  const serverAddress = await new Promise<string>((resolve, reject) => {
    localService.listen(0, "127.0.0.1", () => {
      const boundAddress = localService.address();
      if (!boundAddress || typeof boundAddress === "string") {
        reject(new Error("Failed to resolve local server address."));
        return;
      }

      resolve(`http://127.0.0.1:${boundAddress.port}/health`);
    });
  });

  return {
    healthUrl: serverAddress,
    async close() {
      await new Promise<void>((resolve) => {
        localService.close(() => resolve());
      });
    }
  };
}

describe("control plane app", () => {
  it("returns liveness and readiness metadata", async () => {
    const app = createTestApp();

    const healthResponse = await request(app).get("/health");
    expect(healthResponse.status).toBe(200);
    expect(healthResponse.body.status).toBe("ok");
    expect(typeof healthResponse.headers["x-request-id"]).toBe("string");

    const readyResponse = await request(app).get("/ready");
    expect(readyResponse.status).toBe(200);
    expect(readyResponse.body.status).toBe("ready");
  });

  it("registers module contracts and returns unknown status before telemetry", async () => {
    const app = createTestApp();

    const registerResponse = await request(app)
      .post("/api/modules/register")
      .send(baseModuleContract);

    expect(registerResponse.status).toBe(201);
    expect(registerResponse.body.module.id).toBe("model-hub");

    const statusResponse = await request(app).get("/api/modules/status");
    expect(statusResponse.status).toBe(200);
    expect(statusResponse.body.statuses).toHaveLength(1);
    expect(statusResponse.body.statuses[0].state).toBe("unknown");
  });

  it("computes a healthy score when telemetry is within SLO", async () => {
    const app = createTestApp();

    await request(app)
      .post("/api/modules/register")
      .send(baseModuleContract)
      .expect(201);

    await request(app)
      .post("/api/modules/model-hub/telemetry")
      .send({
        availabilityPct: 99.95,
        latencyP95Ms: 220,
        errorRatePct: 0.2
      })
      .expect(200);

    const statusResponse = await request(app).get("/api/modules/model-hub/status");
    expect(statusResponse.status).toBe(200);
    expect(statusResponse.body.status.state).toBe("healthy");
    expect(statusResponse.body.status.score).toBeGreaterThanOrEqual(85);
  });

  it("computes a critical score when telemetry heavily breaches SLO", async () => {
    const app = createTestApp();

    await request(app)
      .post("/api/modules/register")
      .send(baseModuleContract)
      .expect(201);

    await request(app)
      .post("/api/modules/model-hub/telemetry")
      .send({
        availabilityPct: 93,
        latencyP95Ms: 1500,
        errorRatePct: 7
      })
      .expect(200);

    const statusResponse = await request(app).get("/api/modules/model-hub/status");
    expect(statusResponse.status).toBe(200);
    expect(statusResponse.body.status.state).toBe("critical");
    expect(statusResponse.body.status.reasons.length).toBeGreaterThan(0);
  });

  it("rejects malformed contract payloads", async () => {
    const app = createTestApp();

    const response = await request(app)
      .post("/api/modules/register")
      .send({
        id: "Model Hub",
        name: "",
        category: "platform",
        baseUrl: "javascript:alert('xss')"
      });

    expect(response.status).toBe(400);
    expect(typeof response.body.error).toBe("string");
  });

  it("blocks probe requests to disallowed public origins", async () => {
    const app = createTestApp();

    const response = await request(app)
      .get("/api/health/probe")
      .query({ url: "https://example.com/health" });

    expect(response.status).toBe(403);
    expect(String(response.body.error)).toContain("not allowed");
  });

  it("probes allowed localhost targets and reports online state", async () => {
    const app = createTestApp();

    const localService = createServer((requestMessage, responseMessage) => {
      if (requestMessage.url === "/health") {
        responseMessage.statusCode = 200;
        responseMessage.setHeader("content-type", "application/json");
        responseMessage.end(JSON.stringify({ ok: true }));
        return;
      }

      responseMessage.statusCode = 404;
      responseMessage.end();
    });

    const serverAddress = await new Promise<string>((resolve, reject) => {
      localService.listen(0, "127.0.0.1", () => {
        const boundAddress = localService.address();
        if (!boundAddress || typeof boundAddress === "string") {
          reject(new Error("Failed to resolve local server address."));
          return;
        }

        resolve(`http://127.0.0.1:${boundAddress.port}/health`);
      });
    });

    try {
      const response = await request(app)
        .get("/api/health/probe")
        .query({ url: serverAddress });

      expect(response.status).toBe(200);
      expect(response.body.state).toBe("online");
      expect(response.body.httpStatus).toBe(200);
    } finally {
      await new Promise<void>((resolve) => {
        localService.close(() => resolve());
      });
    }
  });

  it("builds dependency-aware orchestration plans", async () => {
    const app = createTestApp();

    await request(app)
      .post("/api/modules/register")
      .send({
        id: "config-forge",
        name: "config-forge",
        category: "platform",
        baseUrl: "http://localhost:5406",
        healthUrl: "http://localhost:5406/health",
        ownerTeam: "platform-core",
        dependencies: [],
        slo: {
          availabilityPct: 99.9,
          latencyP95Ms: 250,
          errorRatePct: 0.5
        }
      })
      .expect(201);

    await request(app)
      .post("/api/modules/register")
      .send({
        ...baseModuleContract,
        dependencies: ["config-forge"]
      })
      .expect(201);

    await request(app)
      .post("/api/modules/config-forge/telemetry")
      .send({
        availabilityPct: 99.95,
        latencyP95Ms: 210,
        errorRatePct: 0.1
      })
      .expect(200);

    await request(app)
      .post("/api/modules/model-hub/telemetry")
      .send({
        availabilityPct: 99.95,
        latencyP95Ms: 220,
        errorRatePct: 0.2
      })
      .expect(200);

    const response = await request(app)
      .post("/api/orchestration/plan")
      .send({
        targets: ["model-hub"]
      });

    expect(response.status).toBe(200);
    expect(response.body.plan.executionOrder).toEqual(["config-forge", "model-hub"]);
    expect(response.body.plan.stages).toEqual([
      {
        stage: 1,
        moduleIds: ["config-forge"]
      },
      {
        stage: 2,
        moduleIds: ["model-hub"]
      }
    ]);
    expect(response.body.plan.canExecute).toBe(true);
  });

  it("blocks orchestration when policy requires telemetry", async () => {
    const app = createTestApp();

    await request(app)
      .post("/api/modules/register")
      .send(baseModuleContract)
      .expect(201);

    const response = await request(app)
      .post("/api/orchestration/plan")
      .send({
        targets: ["model-hub"],
        policy: {
          requireTelemetry: true
        }
      });

    expect(response.status).toBe(200);
    expect(response.body.plan.canExecute).toBe(false);
    expect(response.body.plan.blockedModules[0].id).toBe("model-hub");
    expect(response.body.plan.blockedModules[0].blockingReasons).toContain(
      "Module has no telemetry and policy requires telemetry."
    );
  });

  it("reports unknown targets in orchestration plan requests", async () => {
    const app = createTestApp();

    const response = await request(app)
      .post("/api/orchestration/plan")
      .send({
        targets: ["missing-module"]
      });

    expect(response.status).toBe(200);
    expect(response.body.plan.unknownTargets).toEqual(["missing-module"]);
    expect(response.body.plan.canExecute).toBe(false);
  });

  it("executes orchestration runs and exposes run lifecycle", async () => {
    const app = createTestApp();

    await request(app)
      .post("/api/modules/register")
      .send({
        id: "config-forge",
        name: "config-forge",
        category: "platform",
        baseUrl: "http://localhost:5406",
        ownerTeam: "platform-core",
        dependencies: [],
        slo: {
          availabilityPct: 99.9,
          latencyP95Ms: 250,
          errorRatePct: 0.5
        }
      })
      .expect(201);

    await request(app)
      .post("/api/modules/register")
      .send({
        ...baseModuleContract,
        healthUrl: undefined,
        dependencies: ["config-forge"]
      })
      .expect(201);

    await request(app)
      .post("/api/modules/config-forge/telemetry")
      .send({
        availabilityPct: 99.95,
        latencyP95Ms: 210,
        errorRatePct: 0.1
      })
      .expect(200);

    await request(app)
      .post("/api/modules/model-hub/telemetry")
      .send({
        availabilityPct: 99.95,
        latencyP95Ms: 220,
        errorRatePct: 0.2
      })
      .expect(200);

    const executeResponse = await request(app)
      .post("/api/orchestration/execute")
      .send({
        targets: ["model-hub"]
      });

    expect(executeResponse.status).toBe(202);
    const runId = executeResponse.body.run.id;
    expect(typeof runId).toBe("string");

    const completedRunResponse = await waitForRunCompletion(app, runId);
    expect(completedRunResponse.body.run.status).toBe("succeeded");
    expect(completedRunResponse.body.run.steps).toHaveLength(2);

    const listedRunsResponse = await request(app)
      .get("/api/orchestration/runs")
      .query({ limit: "5" });

    expect(listedRunsResponse.status).toBe(200);
    expect(listedRunsResponse.body.runs.some((run: { id: string }) => run.id === runId)).toBe(true);
  });

  it("returns blocked execution runs when policy constraints fail", async () => {
    const app = createTestApp();

    await request(app)
      .post("/api/modules/register")
      .send(baseModuleContract)
      .expect(201);

    const response = await request(app)
      .post("/api/orchestration/execute")
      .send({
        targets: ["model-hub"],
        policy: {
          requireTelemetry: true
        }
      });

    expect(response.status).toBe(200);
    expect(response.body.run.status).toBe("blocked");
  });

  it("cancels active orchestration runs", async () => {
    const app = createTestApp();
    const delayedHealthServer = await createDelayedHealthServer();

    try {
      await request(app)
        .post("/api/modules/register")
        .send({
          id: "slow-module",
          name: "slow-module",
          category: "platform",
          baseUrl: "http://localhost:5450",
          healthUrl: delayedHealthServer.healthUrl,
          ownerTeam: "platform-core",
          dependencies: [],
          slo: {
            availabilityPct: 99.9,
            latencyP95Ms: 300,
            errorRatePct: 0.5
          }
        })
        .expect(201);

      const executeResponse = await request(app)
        .post("/api/orchestration/execute")
        .send({
          targets: ["slow-module"]
        });

      expect(executeResponse.status).toBe(202);
      const runId = executeResponse.body.run.id;

      const cancelResponse = await request(app)
        .post(`/api/orchestration/runs/${runId}/cancel`);

      expect(cancelResponse.status === 200 || cancelResponse.status === 202).toBe(true);
      expect(cancelResponse.body.accepted).toBe(true);

      const completedRunResponse = await waitForRunCompletion(app, runId);
      expect(completedRunResponse.body.run.status).toBe("cancelled");
    } finally {
      await delayedHealthServer.close();
    }
  });

  it("retries terminal orchestration runs with linkage metadata", async () => {
    const app = createTestApp();

    await request(app)
      .post("/api/modules/register")
      .send(baseModuleContract)
      .expect(201);

    const blockedRunResponse = await request(app)
      .post("/api/orchestration/execute")
      .send({
        targets: ["model-hub"],
        policy: {
          requireTelemetry: true
        }
      });

    expect(blockedRunResponse.status).toBe(200);
    expect(blockedRunResponse.body.run.status).toBe("blocked");

    const sourceRunId = blockedRunResponse.body.run.id;
    const retryResponse = await request(app)
      .post(`/api/orchestration/runs/${sourceRunId}/retry`);

    expect(retryResponse.status).toBe(200);
    expect(retryResponse.body.run.status).toBe("blocked");
    expect(retryResponse.body.run.retriedFromRunId).toBe(sourceRunId);
  });

  it("rejects retry requests for active orchestration runs", async () => {
    const app = createTestApp();
    const delayedHealthServer = await createDelayedHealthServer();

    try {
      await request(app)
        .post("/api/modules/register")
        .send({
          id: "retry-running-module",
          name: "retry-running-module",
          category: "platform",
          baseUrl: "http://localhost:5451",
          healthUrl: delayedHealthServer.healthUrl,
          ownerTeam: "platform-core",
          dependencies: [],
          slo: {
            availabilityPct: 99.9,
            latencyP95Ms: 300,
            errorRatePct: 0.5
          }
        })
        .expect(201);

      const executeResponse = await request(app)
        .post("/api/orchestration/execute")
        .send({
          targets: ["retry-running-module"]
        });

      expect(executeResponse.status).toBe(202);
      const runId = executeResponse.body.run.id;

      const retryResponse = await request(app)
        .post(`/api/orchestration/runs/${runId}/retry`);

      expect(retryResponse.status).toBe(409);

      await request(app)
        .post(`/api/orchestration/runs/${runId}/cancel`);

      await waitForRunCompletion(app, runId);
    } finally {
      await delayedHealthServer.close();
    }
  });

  it("returns 404 for unknown orchestration run cancellations", async () => {
    const app = createTestApp();

    const response = await request(app).post("/api/orchestration/runs/unknown-run-id/cancel");
    expect(response.status).toBe(404);
    expect(String(response.body.error)).toContain("Unknown orchestration run id");
  });

  it("returns 404 for unknown orchestration run ids", async () => {
    const app = createTestApp();

    const response = await request(app).get("/api/orchestration/runs/unknown-run-id");
    expect(response.status).toBe(404);
    expect(String(response.body.error)).toContain("Unknown orchestration run id");
  });
});
