// Generated by GitHub Copilot

export interface ControlPlaneConfig {
  serviceName: string;
  version: string;
  port: number;
  allowedOrigins: string[];
  allowedProbeOrigins: string[];
  probeTimeoutMs: number;
  requestRateLimitPerMinute: number;
  seedDefaults: boolean;
}

function parsePositiveInt(value: string | undefined, fallbackValue: number): number {
  if (!value) {
    return fallbackValue;
  }

  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallbackValue;
}

function parseBoolean(value: string | undefined, fallbackValue: boolean): boolean {
  if (!value) {
    return fallbackValue;
  }

  const normalized = value.trim().toLowerCase();
  if (normalized === "true" || normalized === "1" || normalized === "yes") {
    return true;
  }

  if (normalized === "false" || normalized === "0" || normalized === "no") {
    return false;
  }

  return fallbackValue;
}

function parseOrigins(value: string | undefined): string[] {
  if (!value || value.trim().length === 0) {
    return ["http://localhost:4300"];
  }

  return value
    .split(",")
    .map((item) => item.trim())
    .filter((item) => item.length > 0);
}

function resolveDefaultProbeOrigins(): string[] {
  return [
    "https://ramdragneel01.github.io",
    "https://github.com"
  ];
}

export function resolveControlPlaneConfig(
  overrides: Partial<ControlPlaneConfig> = {}
): ControlPlaneConfig {
  const rawAllowedOrigins = process.env.ASTRA_ALLOWED_ORIGINS ?? process.env.CORS_ALLOWED_ORIGINS;
  const rawAllowedProbeOrigins = process.env.ASTRA_ALLOWED_PROBE_ORIGINS;

  const allowedOrigins = overrides.allowedOrigins ?? parseOrigins(
    rawAllowedOrigins
  );

  const allowedProbeOrigins = overrides.allowedProbeOrigins ?? (
    rawAllowedProbeOrigins && rawAllowedProbeOrigins.trim().length > 0
      ? parseOrigins(rawAllowedProbeOrigins)
      : resolveDefaultProbeOrigins()
  );

  return {
    serviceName: overrides.serviceName ?? "astramesh-control-plane",
    version: overrides.version ?? process.env.npm_package_version ?? "0.1.0",
    port: overrides.port ?? parsePositiveInt(process.env.ASTRA_CONTROL_PLANE_PORT, 4310),
    allowedOrigins,
    allowedProbeOrigins,
    probeTimeoutMs: overrides.probeTimeoutMs ?? parsePositiveInt(process.env.ASTRA_PROBE_TIMEOUT_MS, 3500),
    requestRateLimitPerMinute:
      overrides.requestRateLimitPerMinute ??
      parsePositiveInt(process.env.ASTRA_REQUESTS_PER_MINUTE, 240),
    seedDefaults: overrides.seedDefaults ?? parseBoolean(process.env.ASTRA_SEED_DEFAULTS, true)
  };
}
