// Generated by GitHub Copilot
import type { ModuleContract, ModuleRecord, ModuleTelemetry } from "./types.js";

export class ModuleRegistry {
  private readonly records = new Map<string, ModuleRecord>();

  upsertContract(contract: ModuleContract): ModuleRecord {
    const now = new Date().toISOString();
    const existing = this.records.get(contract.id);

    const nextRecord: ModuleRecord = {
      ...contract,
      registeredAt: existing?.registeredAt ?? now,
      updatedAt: now,
      telemetry: existing?.telemetry
    };

    this.records.set(contract.id, nextRecord);
    return nextRecord;
  }

  updateTelemetry(moduleId: string, telemetry: ModuleTelemetry): ModuleRecord | null {
    const existing = this.records.get(moduleId);
    if (!existing) {
      return null;
    }

    const nextRecord: ModuleRecord = {
      ...existing,
      telemetry,
      updatedAt: new Date().toISOString()
    };

    this.records.set(moduleId, nextRecord);
    return nextRecord;
  }

  getModule(moduleId: string): ModuleRecord | undefined {
    return this.records.get(moduleId);
  }

  listModules(): ModuleRecord[] {
    return [...this.records.values()].sort((left, right) => left.id.localeCompare(right.id));
  }

  count(): number {
    return this.records.size;
  }

  missingDependencies(moduleRecord: ModuleRecord): string[] {
    return moduleRecord.dependencies.filter((dependencyId) => !this.records.has(dependencyId));
  }
}
