// Generated by GitHub Copilot
import type { ModuleRecord, ModuleStatus } from "./types.js";

function clampScore(value: number): number {
  if (!Number.isFinite(value)) {
    return 0;
  }

  return Math.max(0, Math.min(100, Math.round(value)));
}

export function evaluateModuleStatus(
  moduleRecord: ModuleRecord,
  missingDependencies: string[]
): ModuleStatus {
  const evaluatedAt = new Date().toISOString();
  const reasons: string[] = [];

  if (!moduleRecord.telemetry) {
    return {
      id: moduleRecord.id,
      name: moduleRecord.name,
      state: "unknown",
      score: 0,
      reasons: ["No telemetry reported yet for this module."],
      missingDependencies,
      evaluatedAt,
      breakdown: {
        availabilityScore: 0,
        latencyScore: 0,
        errorScore: 0,
        dependencyPenalty: missingDependencies.length * 12
      }
    };
  }

  const { telemetry, slo } = moduleRecord;

  const availabilityScore = clampScore(
    (telemetry.availabilityPct / Math.max(slo.availabilityPct, 0.01)) * 100
  );

  const latencyScore = clampScore(
    (Math.max(slo.latencyP95Ms, 1) / Math.max(telemetry.latencyP95Ms, 1)) * 100
  );

  const errorScore = clampScore(
    telemetry.errorRatePct <= 0
      ? 100
      : (Math.max(slo.errorRatePct, 0.01) / telemetry.errorRatePct) * 100
  );

  const dependencyPenalty = missingDependencies.length * 12;

  let score = clampScore(
    availabilityScore * 0.5 + latencyScore * 0.3 + errorScore * 0.2 - dependencyPenalty
  );

  if (telemetry.availabilityPct < slo.availabilityPct) {
    reasons.push(
      `Availability ${telemetry.availabilityPct.toFixed(2)}% is below SLO ${slo.availabilityPct.toFixed(2)}%.`
    );
  }

  if (telemetry.latencyP95Ms > slo.latencyP95Ms) {
    reasons.push(
      `Latency p95 ${telemetry.latencyP95Ms.toFixed(0)}ms exceeds SLO ${slo.latencyP95Ms.toFixed(0)}ms.`
    );
  }

  if (telemetry.errorRatePct > slo.errorRatePct) {
    reasons.push(
      `Error rate ${telemetry.errorRatePct.toFixed(2)}% exceeds SLO ${slo.errorRatePct.toFixed(2)}%.`
    );
  }

  if (missingDependencies.length > 0) {
    reasons.push(`Missing dependencies: ${missingDependencies.join(", ")}.`);
  }

  let state: ModuleStatus["state"] = "critical";
  if (score >= 85) {
    state = "healthy";
  } else if (score >= 60) {
    state = "degraded";
  }

  if (missingDependencies.length > 0 && state === "healthy") {
    state = "degraded";
    score = Math.min(score, 79);
  }

  if (reasons.length === 0) {
    reasons.push("All tracked signals are within SLO boundaries.");
  }

  return {
    id: moduleRecord.id,
    name: moduleRecord.name,
    state,
    score,
    reasons,
    missingDependencies,
    evaluatedAt,
    breakdown: {
      availabilityScore,
      latencyScore,
      errorScore,
      dependencyPenalty
    }
  };
}
