// Generated by GitHub Copilot
import type { ModuleContract } from "./types.js";

export const DEFAULT_MODULE_CONTRACTS: ModuleContract[] = [
  {
    id: "drift-watch",
    name: "drift-watch",
    category: "observability",
    baseUrl: "http://localhost:5401",
    healthUrl: "http://localhost:5401",
    ownerTeam: "ml-platform",
    dependencies: ["config-forge"],
    slo: {
      availabilityPct: 99.5,
      latencyP95Ms: 400,
      errorRatePct: 1.0
    }
  },
  {
    id: "config-forge",
    name: "config-forge",
    category: "platform",
    baseUrl: "http://localhost:5406",
    healthUrl: "http://localhost:5406",
    ownerTeam: "platform-core",
    dependencies: [],
    slo: {
      availabilityPct: 99.9,
      latencyP95Ms: 250,
      errorRatePct: 0.5
    }
  },
  {
    id: "prompt-ops",
    name: "prompt-ops",
    category: "agentics",
    baseUrl: "http://localhost:5404",
    healthUrl: "http://localhost:5404",
    ownerTeam: "agentics",
    dependencies: ["config-forge"],
    slo: {
      availabilityPct: 99.7,
      latencyP95Ms: 300,
      errorRatePct: 0.8
    }
  }
];
