// Generated by GitHub Copilot
import { createControlPlaneApp } from "./app.js";

const { app, config } = createControlPlaneApp();

app.listen(config.port, () => {
  console.info(
    JSON.stringify({
      level: "info",
      message: "control-plane.started",
      service: config.serviceName,
      port: config.port,
      allowedOrigins: config.allowedOrigins,
      timestamp: new Date().toISOString()
    })
  );
});
