// Generated by GitHub Copilot

export type ModuleCategory = "platform" | "agentics" | "observability" | "other";

export interface ModuleSLO {
  availabilityPct: number;
  latencyP95Ms: number;
  errorRatePct: number;
}

export interface ModuleContract {
  id: string;
  name: string;
  category: ModuleCategory;
  baseUrl: string;
  healthUrl?: string;
  ownerTeam: string;
  dependencies: string[];
  slo: ModuleSLO;
}

export interface ModuleTelemetry {
  availabilityPct: number;
  latencyP95Ms: number;
  errorRatePct: number;
  observedAt: string;
}

export interface ModuleRecord extends ModuleContract {
  registeredAt: string;
  updatedAt: string;
  telemetry?: ModuleTelemetry;
}

export type ModuleState = "healthy" | "degraded" | "critical" | "unknown";

export interface StatusScoreBreakdown {
  availabilityScore: number;
  latencyScore: number;
  errorScore: number;
  dependencyPenalty: number;
}

export interface ModuleStatus {
  id: string;
  name: string;
  state: ModuleState;
  score: number;
  reasons: string[];
  missingDependencies: string[];
  evaluatedAt: string;
  breakdown: StatusScoreBreakdown;
}
