// Generated by GitHub Copilot
import type { ModuleCategory, ModuleContract, ModuleTelemetry, ModuleSLO } from "./types.js";

interface ParseSuccess<T> {
  ok: true;
  value: T;
}

interface ParseError {
  ok: false;
  error: string;
}

type ParseResult<T> = ParseSuccess<T> | ParseError;

const ALLOWED_CATEGORIES = new Set<ModuleCategory>([
  "platform",
  "agentics",
  "observability",
  "other"
]);

function asObject(value: unknown): Record<string, unknown> | null {
  return typeof value === "object" && value !== null ? (value as Record<string, unknown>) : null;
}

function asNonEmptyString(value: unknown, fieldName: string): ParseResult<string> {
  if (typeof value !== "string" || value.trim().length === 0) {
    return { ok: false, error: `${fieldName} must be a non-empty string.` };
  }

  return { ok: true, value: value.trim() };
}

function asNumber(value: unknown, fieldName: string, minValue: number): ParseResult<number> {
  if (typeof value !== "number" || !Number.isFinite(value) || value < minValue) {
    return { ok: false, error: `${fieldName} must be a number >= ${minValue}.` };
  }

  return { ok: true, value };
}

function validateHttpUrl(rawUrl: string, fieldName: string): ParseResult<string> {
  try {
    const parsed = new URL(rawUrl);
    if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
      return { ok: false, error: `${fieldName} must use http or https protocol.` };
    }

    return { ok: true, value: parsed.toString().replace(/\/$/, "") };
  } catch {
    return { ok: false, error: `${fieldName} must be a valid URL.` };
  }
}

function parseSLO(input: unknown): ParseResult<ModuleSLO> {
  const asRecord = asObject(input);
  if (!asRecord) {
    return { ok: false, error: "slo must be an object." };
  }

  const availability = asNumber(asRecord.availabilityPct, "slo.availabilityPct", 0);
  if (!availability.ok) {
    return availability;
  }

  const latency = asNumber(asRecord.latencyP95Ms, "slo.latencyP95Ms", 1);
  if (!latency.ok) {
    return latency;
  }

  const errorRate = asNumber(asRecord.errorRatePct, "slo.errorRatePct", 0);
  if (!errorRate.ok) {
    return errorRate;
  }

  return {
    ok: true,
    value: {
      availabilityPct: availability.value,
      latencyP95Ms: latency.value,
      errorRatePct: errorRate.value
    }
  };
}

export function parseModuleContractPayload(input: unknown): ParseResult<ModuleContract> {
  const asRecord = asObject(input);
  if (!asRecord) {
    return { ok: false, error: "Request body must be an object." };
  }

  const id = asNonEmptyString(asRecord.id, "id");
  if (!id.ok) {
    return id;
  }

  if (!/^[a-z0-9-]+$/.test(id.value)) {
    return {
      ok: false,
      error: "id must contain only lowercase letters, numbers, and hyphens."
    };
  }

  const name = asNonEmptyString(asRecord.name, "name");
  if (!name.ok) {
    return name;
  }

  const category = asNonEmptyString(asRecord.category, "category");
  if (!category.ok) {
    return category;
  }

  if (!ALLOWED_CATEGORIES.has(category.value as ModuleCategory)) {
    return {
      ok: false,
      error: `category must be one of: ${[...ALLOWED_CATEGORIES].join(", ")}.`
    };
  }

  const baseUrl = asNonEmptyString(asRecord.baseUrl, "baseUrl");
  if (!baseUrl.ok) {
    return baseUrl;
  }

  const validatedBaseUrl = validateHttpUrl(baseUrl.value, "baseUrl");
  if (!validatedBaseUrl.ok) {
    return validatedBaseUrl;
  }

  const ownerTeam = asNonEmptyString(asRecord.ownerTeam, "ownerTeam");
  if (!ownerTeam.ok) {
    return ownerTeam;
  }

  const dependenciesValue = asRecord.dependencies;
  const dependencies: string[] = [];
  if (Array.isArray(dependenciesValue)) {
    for (const dependency of dependenciesValue) {
      const parsedDependency = asNonEmptyString(dependency, "dependencies[]");
      if (!parsedDependency.ok) {
        return parsedDependency;
      }

      dependencies.push(parsedDependency.value);
    }
  } else if (dependenciesValue !== undefined) {
    return { ok: false, error: "dependencies must be an array of strings." };
  }

  const parsedSLO = parseSLO(asRecord.slo);
  if (!parsedSLO.ok) {
    return parsedSLO;
  }

  let healthUrl: string | undefined;
  if (asRecord.healthUrl !== undefined) {
    const rawHealthUrl = asNonEmptyString(asRecord.healthUrl, "healthUrl");
    if (!rawHealthUrl.ok) {
      return rawHealthUrl;
    }

    const validatedHealthUrl = validateHttpUrl(rawHealthUrl.value, "healthUrl");
    if (!validatedHealthUrl.ok) {
      return validatedHealthUrl;
    }

    healthUrl = validatedHealthUrl.value;
  }

  return {
    ok: true,
    value: {
      id: id.value,
      name: name.value,
      category: category.value as ModuleCategory,
      baseUrl: validatedBaseUrl.value,
      healthUrl,
      ownerTeam: ownerTeam.value,
      dependencies,
      slo: parsedSLO.value
    }
  };
}

export function parseTelemetryPayload(input: unknown): ParseResult<ModuleTelemetry> {
  const asRecord = asObject(input);
  if (!asRecord) {
    return { ok: false, error: "Request body must be an object." };
  }

  const availability = asNumber(asRecord.availabilityPct, "availabilityPct", 0);
  if (!availability.ok) {
    return availability;
  }

  const latency = asNumber(asRecord.latencyP95Ms, "latencyP95Ms", 1);
  if (!latency.ok) {
    return latency;
  }

  const errorRate = asNumber(asRecord.errorRatePct, "errorRatePct", 0);
  if (!errorRate.ok) {
    return errorRate;
  }

  let observedAt = new Date().toISOString();
  if (typeof asRecord.observedAt === "string") {
    const parsedTimestamp = new Date(asRecord.observedAt);
    if (!Number.isNaN(parsedTimestamp.getTime())) {
      observedAt = parsedTimestamp.toISOString();
    }
  }

  return {
    ok: true,
    value: {
      availabilityPct: availability.value,
      latencyP95Ms: latency.value,
      errorRatePct: errorRate.value,
      observedAt
    }
  };
}
