// Generated by GitHub Copilot
import { describe, expect, it } from "vitest";
import type { ProjectIntegration } from "../types";
import { filterProjectsByRole } from "./access";

const SAMPLE_PROJECTS: ProjectIntegration[] = [
  {
    id: "p1",
    name: "platform-one",
    tagline: "tagline",
    category: "platform",
    kind: "frontend",
    launchMode: "iframe",
    url: "http://localhost:5401",
    startCommand: "npm run dev",
    repoPath: "..\\sample",
    statusNote: "sample",
    allowedRoles: ["admin", "platform-ops"]
  },
  {
    id: "p2",
    name: "obs-one",
    tagline: "tagline",
    category: "observability",
    kind: "frontend",
    launchMode: "iframe",
    url: "http://localhost:5402",
    startCommand: "npm run dev",
    repoPath: "..\\sample",
    statusNote: "sample",
    allowedRoles: ["admin", "ml-ops", "viewer"]
  }
];

describe("filterProjectsByRole", () => {
  it("returns projects visible to selected role", () => {
    const visibleProjects = filterProjectsByRole(SAMPLE_PROJECTS, "platform-ops");
    expect(visibleProjects.map((project) => project.id)).toEqual(["p1"]);
  });

  it("returns empty list when role has no access", () => {
    const visibleProjects = filterProjectsByRole(SAMPLE_PROJECTS, "research");
    expect(visibleProjects).toHaveLength(0);
  });
});
