// Generated by GitHub Copilot
import type { ProjectIntegration, UserRole } from "../types";

const ROLE_STORAGE_KEY = "astramesh.userRole";

export interface RoleOption {
  value: UserRole;
  label: string;
}

export const ROLE_OPTIONS: RoleOption[] = [
  { value: "admin", label: "Admin" },
  { value: "platform-ops", label: "Platform Ops" },
  { value: "ml-ops", label: "ML Ops" },
  { value: "research", label: "Research" },
  { value: "viewer", label: "Viewer" }
];

export const DEFAULT_ROLE: UserRole = "admin";

/**
 * Resolves a safe default role from environment settings.
 */
function resolveConfiguredDefaultRole(): UserRole {
  const configuredRole = import.meta.env.VITE_DEFAULT_USER_ROLE as UserRole | undefined;
  if (!configuredRole) {
    return DEFAULT_ROLE;
  }

  const knownRole = ROLE_OPTIONS.some((role) => role.value === configuredRole);
  return knownRole ? configuredRole : DEFAULT_ROLE;
}

/**
 * Filters modules to those visible to the selected role.
 */
export function filterProjectsByRole(
  projects: ProjectIntegration[],
  activeRole: UserRole
): ProjectIntegration[] {
  return projects.filter((project) => project.allowedRoles.includes(activeRole));
}

/**
 * Reads role from browser storage while keeping SSR-safe behavior.
 */
export function getStoredRole(): UserRole {
  if (typeof window === "undefined") {
    return resolveConfiguredDefaultRole();
  }

  const savedRole = window.localStorage.getItem(ROLE_STORAGE_KEY) as UserRole | null;
  if (!savedRole) {
    return resolveConfiguredDefaultRole();
  }

  const knownRole = ROLE_OPTIONS.some((role) => role.value === savedRole);
  return knownRole ? savedRole : resolveConfiguredDefaultRole();
}

/**
 * Persists role selection so navigation stays stable across sessions.
 */
export function setStoredRole(nextRole: UserRole): void {
  if (typeof window === "undefined") {
    return;
  }

  window.localStorage.setItem(ROLE_STORAGE_KEY, nextRole);
}
