// Generated by GitHub Copilot
import type { ThemeMode } from "../types";

const THEME_STORAGE_KEY = "astramesh.themeMode";

/**
 * Reads configured default theme from environment while enforcing accepted values.
 */
function getConfiguredDefaultTheme(): ThemeMode {
    const configuredTheme = import.meta.env.VITE_DEFAULT_THEME?.trim().toLowerCase();
    return configuredTheme === "dark" ? "dark" : "light";
}

/**
 * Resolves browser preference if available; otherwise returns null.
 */
function getSystemPreferredTheme(): ThemeMode | null {
    if (typeof window === "undefined" || typeof window.matchMedia !== "function") {
        return null;
    }

    return window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
}

/**
 * Returns the active theme from storage, system preference, or environment default.
 */
export function getStoredThemeMode(): ThemeMode {
    if (typeof window === "undefined") {
        return getConfiguredDefaultTheme();
    }

    const storedTheme = window.localStorage.getItem(THEME_STORAGE_KEY);
    if (storedTheme === "light" || storedTheme === "dark") {
        return storedTheme;
    }

    return getSystemPreferredTheme() ?? getConfiguredDefaultTheme();
}

/**
 * Saves theme mode for future sessions.
 */
export function setStoredThemeMode(nextMode: ThemeMode): void {
    if (typeof window === "undefined") {
        return;
    }

    window.localStorage.setItem(THEME_STORAGE_KEY, nextMode);
}

/**
 * Applies theme mode to document root so CSS variables can switch instantly.
 */
export function applyThemeMode(nextMode: ThemeMode): void {
    if (typeof document === "undefined") {
        return;
    }

    document.documentElement.setAttribute("data-theme", nextMode);
    document.documentElement.style.colorScheme = nextMode;
}
