// Generated by GitHub Copilot
import { beforeEach, describe, expect, it } from "vitest";
import { applyThemeMode, getStoredThemeMode, setStoredThemeMode } from "./theme";

describe("theme utils", () => {
    beforeEach(() => {
        window.localStorage.clear();
        document.documentElement.removeAttribute("data-theme");
        document.documentElement.style.colorScheme = "";
    });

    it("stores and retrieves theme from localStorage", () => {
        setStoredThemeMode("dark");
        expect(getStoredThemeMode()).toBe("dark");
    });

    it("applies theme mode to document root", () => {
        applyThemeMode("dark");
        expect(document.documentElement.getAttribute("data-theme")).toBe("dark");
        expect(document.documentElement.style.colorScheme).toBe("dark");
    });

    it("falls back to light when nothing is configured", () => {
        expect(getStoredThemeMode()).toBe("light");
    });
});
