// Generated by GitHub Copilot

const ALLOWED_PROTOCOLS = new Set(["http:", "https:"]);
const DEFAULT_ALLOWED_ORIGINS = new Set([
  "http://localhost:4300",
  "http://localhost:5401",
  "http://localhost:5402",
  "http://localhost:5403",
  "http://localhost:5404",
  "http://localhost:5405",
  "http://localhost:5406",
  "http://localhost:5407",
  "http://localhost:5408",
  "http://localhost:5409",
  "http://localhost:5410",
  "http://localhost:6006",
  "https://ramdragneel01.github.io",
  "https://github.com"
]);

/**
 * Resolves origin allowlist from environment, with secure local/prod defaults.
 */
export function resolveAllowedOrigins(): Set<string> {
  const configuredAllowlist = import.meta.env.VITE_ALLOWED_IFRAME_ORIGINS;
  if (!configuredAllowlist) {
    return DEFAULT_ALLOWED_ORIGINS;
  }

  const origins = configuredAllowlist
    .split(",")
    .map((value) => value.trim())
    .filter((value) => value.length > 0);

  if (origins.length === 0) {
    return DEFAULT_ALLOWED_ORIGINS;
  }

  return new Set(origins);
}

/**
 * Returns a normalized URL only when protocol and origin are allowed.
 * This prevents unsafe iframe/external navigation schemes.
 */
export function normalizeProjectUrl(
  rawUrl: string,
  allowedOrigins: Set<string> = resolveAllowedOrigins()
): string | null {
  try {
    const parsedUrl = new URL(rawUrl);
    if (!ALLOWED_PROTOCOLS.has(parsedUrl.protocol)) {
      return null;
    }

    if (!allowedOrigins.has(parsedUrl.origin)) {
      return null;
    }

    return parsedUrl.toString();
  } catch {
    return null;
  }
}
