// Generated by GitHub Copilot

const ALLOWED_PROTOCOLS = new Set(["http:", "https:"]);

/**
 * Returns a normalized URL only when protocol is allowed.
 * This prevents unsafe iframe/external navigation schemes.
 */
export function normalizeProjectUrl(rawUrl: string): string | null {
  try {
    const parsedUrl = new URL(rawUrl);
    if (!ALLOWED_PROTOCOLS.has(parsedUrl.protocol)) {
      return null;
    }
    return parsedUrl.toString();
  } catch {
    return null;
  }
}
