// Generated by GitHub Copilot
import { describe, expect, it } from "vitest";
import { normalizeProjectUrl } from "./url";

describe("normalizeProjectUrl", () => {
  it("accepts http and https urls", () => {
    expect(normalizeProjectUrl("http://localhost:4300")).toContain("http://localhost:4300");
    expect(normalizeProjectUrl("https://example.com")).toContain("https://example.com");
  });

  it("rejects javascript pseudo urls", () => {
    expect(normalizeProjectUrl("javascript:alert(1)")).toBeNull();
  });

  it("rejects malformed values", () => {
    expect(normalizeProjectUrl("not-a-url")).toBeNull();
  });
});
